# Generated by Django 6.0.1 on 2026-01-26 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], max_length=20)),
                ('amount_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.IntegerField()),
                ('request_type', models.CharField(choices=[('custom', 'Custom'), ('direct', 'Direct'), ('emergency', 'Emergency')], max_length=20)),
                ('request_status', models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('service_location_id', models.IntegerField()),
                ('service_time_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('before_picture_service', models.ImageField(blank=True, null=True, upload_to='bookings/before/')),
                ('after_picture_service', models.ImageField(blank=True, null=True, upload_to='bookings/after/')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='CustomRequest',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookings.request')),
                ('description', models.TextField()),
                ('concern_picture', models.ImageField(blank=True, null=True, upload_to='requests/custom/')),
                ('providers_note', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.request'),
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField()),
                ('issue_picture', models.ImageField(blank=True, null=True, upload_to='disputes/')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('complainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_disputes', to='users.account')),
                ('complaint_against', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_disputes', to='users.account')),
            ],
        ),
        migrations.CreateModel(
            name='QuotedRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custom_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.customrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DirectRequest',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookings.request')),
                ('add_ons', models.ManyToManyField(blank=True, to='services.serviceaddon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
