# Generated by Django 6.0.1 on 2026-01-28 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('services', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='directrequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AddField(
            model_name='directrequestaddon',
            name='service_add_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.serviceaddon'),
        ),
        migrations.AddField(
            model_name='disputebooking',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.admin'),
        ),
        migrations.AddField(
            model_name='disputebooking',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='disputebooking',
            name='complainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_made', to='users.account'),
        ),
        migrations.AddField(
            model_name='disputebooking',
            name='complaint_against',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_received', to='users.account'),
        ),
        migrations.AddField(
            model_name='disputebooking',
            name='refund_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='users.account'),
        ),
        migrations.AddField(
            model_name='request',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
        migrations.AddField(
            model_name='request',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provided_requests', to='users.account'),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.request'),
        ),
        migrations.AddField(
            model_name='directrequestaddon',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.request'),
        ),
        migrations.AddField(
            model_name='directrequest',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.request'),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.request'),
        ),
        migrations.AddField(
            model_name='booking',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.request'),
        ),
        migrations.AddField(
            model_name='reworkbooking',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='reworkbooking',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rework_requests', to='users.account'),
        ),
        migrations.AddField(
            model_name='request',
            name='service_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.servicelocation'),
        ),
    ]
