# Generated by Django 6.0.1 on 2026-02-19 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_add_cancelled_status'),
        ('services', '0004_rename_services_me_mechani_idx_services_me_mechani_d6a199_idx_and_more'),
        ('users', '0004_mechanic_bio_mechanicreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('custom', 'Custom'), ('direct', 'Direct'), ('emergency', 'Emergency'), ('broadcast', 'Broadcast')], max_length=20),
        ),
        migrations.CreateModel(
            name='BroadcastRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('concern_picture', models.ImageField(blank=True, null=True, upload_to='requests/broadcast/')),
                ('status', models.CharField(choices=[('searching', 'Searching'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='searching', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_request', to='bookings.request')),
                ('services', models.ManyToManyField(related_name='broadcast_requests', to='services.service')),
            ],
            options={
                'db_table': 'bookings_broadcastrequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_offers', to='users.mechanic')),
                ('broadcast_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='bookings.broadcastrequest')),
            ],
            options={
                'db_table': 'bookings_broadcastoffer',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastRequestAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='bookings.broadcastrequest')),
                ('service_add_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_requests', to='services.serviceaddon')),
            ],
            options={
                'db_table': 'bookings_broadcastrequestaddon',
            },
        ),
        migrations.AddIndex(
            model_name='broadcastrequest',
            index=models.Index(fields=['status', 'expires_at'], name='bookings_br_status_c62e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastrequest',
            index=models.Index(fields=['latitude', 'longitude'], name='bookings_br_latitud_818161_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastoffer',
            index=models.Index(fields=['broadcast_request', 'status'], name='bookings_br_broadca_3cb812_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastoffer',
            index=models.Index(fields=['mechanic', 'created_at'], name='bookings_br_mechani_0f21b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='broadcastoffer',
            unique_together={('broadcast_request', 'mechanic')},
        ),
        migrations.AlterUniqueTogether(
            name='broadcastrequestaddon',
            unique_together={('broadcast_request', 'service_add_on')},
        ),
    ]
