# Generated by Django 6.0.1 on 2026-02-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_request_request_type_broadcastrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastoffer',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance from mechanic to service location in kilometers', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='broadcastoffer',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated total price: service minimum prices + distance charge (₱10/km, min 5km)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='broadcastoffer',
            name='mechanic_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='broadcastoffer',
            name='mechanic_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
