# Generated by Django 4.2.11 on 2026-02-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_broadcastoffer_distance_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('on_the_way', 'On The Way'), ('active', 'Active'), ('completed', 'Completed'), ('reworked', 'Reworked'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='active', max_length=20),
        ),
    ]
