# Generated by Django 4.2.11 on 2026-03-02 18:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activebooking',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activebooking',
            name='total_pause_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('on_the_way', 'On The Way'), ('active', 'Active'), ('paused', 'Paused'), ('finished', 'Finished'), ('pending_payment', 'Pending Payment'), ('completed', 'Completed'), ('reworked', 'Reworked'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_received', models.BooleanField(default=False)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='bookings/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
            ],
        ),
    ]
