# Generated by Django 4.2.11 on 2026-03-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_activebooking_paused_at_and_more'),
    ]

    operations = [
        # Use conditional SQL so applying the migration is idempotent
        migrations.RunSQL(
            sql=(
                "ALTER TABLE bookings_activebooking "
                "ADD COLUMN IF NOT EXISTS stage varchar(50) NOT NULL DEFAULT ''"
            ),
            reverse_sql=(
                "ALTER TABLE bookings_activebooking "
                "DROP COLUMN IF EXISTS stage"
            ),
        ),
    ]
