# Generated by Django 4.2.11 on 2026-03-02 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_activebooking_stage_updated_at'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE bookings_activebooking "
                "ADD COLUMN IF NOT EXISTS stage varchar(50) NOT NULL DEFAULT ''; "
                "ALTER TABLE bookings_activebooking "
                "ADD COLUMN IF NOT EXISTS stage_updated_at timestamp with time zone NOT NULL DEFAULT now();"
            ),
            reverse_sql=(
                "ALTER TABLE bookings_activebooking DROP COLUMN IF EXISTS stage_updated_at; "
                "ALTER TABLE bookings_activebooking DROP COLUMN IF EXISTS stage;"
            ),
        ),
    ]
