# Generated by Django 4.2.11 on 2026-03-08 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_tokentransaction'),
        ('bookings', '0011_separate_state_add_activebooking_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(blank=True, choices=[('lead', 'Lead'), ('assistant', 'Assistant')], default='assistant', max_length=50)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_assignments', to='users.account')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bookings.request')),
            ],
            options={
                'unique_together': {('request', 'mechanic')},
            },
        ),
    ]
