# Generated by Django 6.0.1 on 2026-03-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_requestassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
