# Generated by Django 6.0.1 on 2026-03-11 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_quotation_quotationitem'),
        ('bookings', '0014_servicelocation_latitude_servicelocation_longitude'),
    ]

    operations = [
    ]
