# Generated by Django 6.0.1 on 2026-03-11 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_merge_20260312_0721'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_requests', to='shops.shop'),
        ),
    ]
