# Generated by Django 6.0.1 on 2026-03-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_backjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backjob',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='backjob',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('on_the_way', 'On The Way'), ('active', 'Active'), ('paused', 'Paused'), ('finished', 'Finished'), ('pending_payment', 'Pending Payment'), ('completed', 'Completed'), ('reworked', 'Reworked'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='accepted', max_length=30),
        ),
    ]
