# Generated by Django 6.0.1 on 2026-03-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_alter_backjob_id_alter_backjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'cash'), ('online', 'online')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='receipt',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
