# Generated by Django 6.0.1 on 2026-03-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_receipt_payment_method_receipt_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastoffer',
            name='convenience_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated convenience fee (base + distance + traffic surcharge)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='broadcastoffer',
            name='estimated_eta_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated travel time in minutes from ORS when mechanic viewed', null=True),
        ),
        migrations.AddField(
            model_name='broadcastoffer',
            name='traffic_level',
            field=models.CharField(blank=True, help_text='Traffic level when mechanic viewed: light/moderate/heavy/severe', max_length=20, null=True),
        ),
    ]
