# Generated by Django 6.0.1 on 2026-03-21 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_broadcastoffer_convenience_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='convenience_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Locked convenience fee when mechanic pressed On The Way', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Road distance in km from ORS when mechanic went On The Way', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='eta_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated travel time in minutes from ORS when fee was locked', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='fee_locked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when mechanic pressed On The Way and fee was locked', null=True),
        ),
        migrations.CreateModel(
            name='MechanicLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Mechanic current latitude', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Mechanic current longitude', max_digits=9)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time location was updated')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_location', to='bookings.booking')),
            ],
            options={
                'db_table': 'bookings_mechaniclocation',
            },
        ),
    ]
