# Generated by Django 6.0.1 on 2026-03-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_booking_convenience_fee_booking_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='traffic_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Real traffic surcharge added when mechanic went OTW', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Road distance in km from ORS when mechanic accepted the booking', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='broadcastoffer',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance from mechanic to service location in kilometers when accepted', max_digits=6, null=True),
        ),
    ]
