# Generated by assistant on 2026-04-08
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_booking_traffic_surcharge_alter_booking_distance_km_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE bookings_broadcastrequest
            ALTER COLUMN search_radius_km DROP NOT NULL;
            """,
            reverse_sql="""
            ALTER TABLE bookings_broadcastrequest
            ALTER COLUMN search_radius_km SET NOT NULL;
            """,
        ),
    ]
