# Generated by ChatGPT - add Quotation.status field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_booking_traffic_surcharge_alter_booking_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(default='pending', choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('rejected', 'REJECTED')], max_length=20),
        ),
    ]
