# Generated by Django 6.0.1 on 2026-04-13 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_quotationitem_change_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='ewallet_source_id',
            field=models.CharField(blank=True, help_text='PayMongo payment source ID for e-wallet', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ewallet_type',
            field=models.CharField(blank=True, choices=[('gcash', 'GCash'), ('maya', 'Maya')], help_text='E-wallet type if payment_method is gcash or maya', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='mechanic_payout',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount disbursed to mechanic or shop owner', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when payment was confirmed', null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='platform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base fee deducted as platform earnings', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('maya', 'Maya')], default='cash', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentQRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(help_text='Unique signed UUID for QR code', unique=True)),
                ('is_used', models.BooleanField(default=False, help_text='True after client confirms payment')),
                ('expires_at', models.DateTimeField(help_text='24 hours after booking marked FINISHED')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_token', to='bookings.booking')),
            ],
            options={
                'db_table': 'bookings_paymentqrtoken',
            },
        ),
    ]
