# Generated by Django 6.0.1 on 2026-04-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0028_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dispute_status',
            field=models.CharField(choices=[('none', 'None'), ('active', 'Active'), ('resolved', 'Resolved')], default='none', help_text='Parallel dispute lifecycle state; does not replace booking status', max_length=20),
        ),
    ]
