# Generated by Django 6.0.1 on 2026-04-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0029_booking_dispute_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputebooking',
            name='is_client_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disputebooking',
            name='refund_receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='bookings/disputes/refunds/'),
        ),
        migrations.AlterField(
            model_name='disputebooking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('waiting_for_mechanic_payment', 'Waiting For Mechanic Payment'), ('waiting_for_client_verification', 'Waiting For Client Verification'), ('resolved_refunded', 'Resolved Refunded'), ('resolved_dismissed', 'Resolved Dismissed'), ('resolved_voucher', 'Resolved Voucher')], default='active', max_length=50),
        ),
    ]
