# Generated by Django 6.0.1 on 2026-04-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0030_disputebooking_is_client_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputebooking',
            name='refund_account_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='disputebooking',
            name='refund_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disputebooking',
            name='refund_method',
            field=models.CharField(blank=True, choices=[('gcash', 'Gcash'), ('maya', 'Maya'), ('voucher', 'Voucher')], max_length=20, null=True),
        ),
    ]
