# Generated by Django 6.0.1 on 2026-04-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0031_disputebooking_refund_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disputebooking',
            name='refund_account_name',
        ),
    ]
