# Generated by Django 6.0.1 on 2026-04-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0033_disputebooking_mechanic_defense_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backjob',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('on_the_way', 'On The Way'), ('at_location', 'At Location'), ('diagnosing', 'Diagnosing'), ('active', 'Active'), ('paused', 'Paused'), ('finished', 'Finished'), ('pending_payment', 'Pending Payment'), ('completed', 'Completed'), ('reworked', 'Reworked'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='accepted', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('on_the_way', 'On The Way'), ('at_location', 'At Location'), ('diagnosing', 'Diagnosing'), ('active', 'Active'), ('paused', 'Paused'), ('finished', 'Finished'), ('pending_payment', 'Pending Payment'), ('completed', 'Completed'), ('reworked', 'Reworked'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='active', max_length=20),
        ),
    ]
