# Generated by Django 6.0.1 on 2026-04-25 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0043_quotationitem_created_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='backjob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='bookings.backjob'),
        ),
        migrations.AlterField(
            model_name='backjob',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backjobs', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
