# Generated by Django 6.0.1 on 2026-04-26 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0045_quotationamendment_amendmentitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bookings/disputes/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bookings.disputebooking')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
