# Generated by Django 6.0.1 on 2026-04-26 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0047_directrequestserviceline'),
        ('users', '0027_smsotpverification_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='activebooking',
            name='pre_reschedule_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activebooking',
            name='proposed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activebooking',
            name='reschedule_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_requests', to='users.account'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backjob',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('accepted', 'Accepted'), ('pending', 'Pending'), ('reschedule_proposed', 'Reschedule Proposed'), ('on_the_way', 'On The Way'), ('at_location', 'At Location'), ('diagnosing', 'Diagnosing'), ('active', 'Active'), ('paused', 'Paused'), ('finished', 'Finished'), ('pending_payment', 'Pending Payment'), ('completed', 'Completed'), ('backjob_pending', 'Backjob Pending'), ('reworked', 'Reworked'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='accepted', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('accepted', 'Accepted'), ('pending', 'Pending'), ('reschedule_proposed', 'Reschedule Proposed'), ('on_the_way', 'On The Way'), ('at_location', 'At Location'), ('diagnosing', 'Diagnosing'), ('active', 'Active'), ('paused', 'Paused'), ('finished', 'Finished'), ('pending_payment', 'Pending Payment'), ('completed', 'Completed'), ('backjob_pending', 'Backjob Pending'), ('reworked', 'Reworked'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='active', max_length=20),
        ),
    ]
