# Generated by Django 6.0.1 on 2026-04-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0048_activebooking_pre_reschedule_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
