# Generated by Django 6.0.1 on 2026-04-27 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0046_disputeimage'),
        ('bookings', '0049_request_scheduled_time'),
    ]

    operations = [
    ]
