# Generated by Django 6.0.1 on 2026-04-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0050_merge_0046_disputeimage_0049_request_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinstallment',
            name='installment_type',
            field=models.CharField(choices=[('initial', 'Initial'), ('final', 'Final'), ('full', 'Full'), ('partial', 'Partial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='method',
            field=models.CharField(choices=[('qr', 'Qr'), ('gcash', 'Gcash'), ('maya', 'Maya'), ('credits', 'Credits')], max_length=20),
        ),
    ]
