# Generated by Django 6.0.1 on 2026-04-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0052_broadcastoffer_shop_nullable_mechanic'),
        ('shops', '0002_shopmechanic_is_active'),
        ('users', '0027_smsotpverification_account'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='broadcastoffer',
            index=models.Index(fields=['shop', 'created_at'], name='bookings_br_shop_id_21231c_idx'),
        ),
    ]
