# Generated by Django 6.0.1 on 2026-04-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0053_broadcastoffer_bookings_br_shop_id_21231c_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='source',
            field=models.CharField(blank=True, choices=[('on_hand', 'On-hand (mechanic stock)'), ('to_be_purchased', 'To be purchased'), ('already_purchased', 'Already purchased (have receipt)'), ('mechanic_selling', 'Mechanic selling / owned spare')], max_length=30, null=True),
        ),
    ]
