import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#111214',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 50,
    paddingBottom: 12,
    backgroundColor: '#1A1C1E',
    borderBottomWidth: 1,
    borderBottomColor: '#2A2C2E',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FF8C0015',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
  },
  backjobBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FF8C00',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    marginHorizontal: 16,
    marginBottom: 12,
  },
  backjobText: {
    color: '#fff',
    fontWeight: '700',
    marginLeft: 4,
  },
  backjobReason: {
    color: '#FFF7EA',
    marginLeft: 8,
    flex: 1,
    fontSize: 12,
  },
  refreshBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FF8C0015',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  errorText: {
    fontSize: 16,
    color: '#FF3B30',
    marginTop: 16,
    textAlign: 'center',
  },
  retryButton: {
    marginTop: 16,
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: '#FF8C00',
    borderRadius: 10,
  },
  retryText: {
    color: '#fff',
    fontWeight: '600',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 220,
  },
  statusCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A1C1E',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
  },
  statusIconLarge: {
    width: 56,
    height: 56,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  statusInfo: {
    flex: 1,
  },
  statusBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
  },
  statusBadgeText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#fff',
    letterSpacing: 0.5,
  },
  bookingIdText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#666',
  },
  serviceType: {
    fontSize: 15,
    fontWeight: '600',
    color: '#ccc',
  },
  amountLarge: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#34C759',
  },
  sectionCard: {
    backgroundColor: '#1A1C1E',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#2A2C2E',
  },
  pendingSectionCard: {
    borderColor: '#5D4A26',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  sectionIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
    flex: 1,
  },
  paymentStatusBadge: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  paymentStatusBadgeText: {
    fontSize: 11,
    fontWeight: '700',
  },
  initialPaidBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#2D4B35',
    backgroundColor: '#1D2C22',
    marginBottom: 10,
  },
  initialPaidBannerText: {
    color: '#9FE4B0',
    fontSize: 12,
    fontWeight: '700',
  },
  paymentSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  paymentSummaryLabel: {
    fontSize: 12,
    color: '#8E8E93',
  },
  paymentSummaryValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#ECEDEE',
  },
  installmentListWrap: {
    marginTop: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#2A2C2E',
    backgroundColor: '#17191B',
    overflow: 'hidden',
  },
  installmentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 9,
    borderBottomWidth: 1,
    borderBottomColor: '#232628',
  },
  installmentLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  installmentRight: {
    alignItems: 'flex-end',
  },
  installmentTitle: {
    fontSize: 12,
    color: '#ECEDEE',
    fontWeight: '700',
  },
  installmentAmount: {
    fontSize: 12,
    color: '#ECEDEE',
    fontWeight: '700',
  },
  installmentStatusText: {
    marginTop: 2,
    fontSize: 11,
    fontWeight: '600',
  },
  compactEditButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#2A2C2E',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#3A3D40',
  },
  compactEditButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#fff',
  },
  pendingHintBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
    backgroundColor: '#332A1D',
    borderWidth: 1,
    borderColor: '#5D4A26',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  pendingHintText: {
    color: '#E6C58B',
    fontSize: 12,
    fontWeight: '600',
  },
  infoGrid: {
    gap: 10,
  },
  infoItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  infoLabel: {
    fontSize: 13,
    color: '#8E8E93',
  },
  infoValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#ddd',
  },
  locationDetails: {
    gap: 8,
    marginBottom: 14,
  },
  locationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  locationLabel: {
    fontSize: 13,
    color: '#8E8E93',
    width: 100,
  },
  locationValue: {
    fontSize: 14,
    fontWeight: '500',
    color: '#ddd',
    flex: 1,
    textAlign: 'right',
  },
  navigateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF8C0012',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: '#FF8C0030',
  },
  navigateIconCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#FF8C00',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  navigateTextContainer: {
    flex: 1,
  },
  navigateTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FF8C00',
  },
  navigateSubtitle: {
    fontSize: 11,
    color: '#8E8E93',
    marginTop: 1,
  },
  noLocationCard: {
    alignItems: 'center',
    padding: 20,
    gap: 8,
  },
  noLocationText: {
    fontSize: 13,
    color: '#666',
  },
  timeline: {
    paddingLeft: 4,
  },
  timelineItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  timelineDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  timelineContent: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  timelineLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#ccc',
  },
  timelineDate: {
    fontSize: 12,
    color: '#8E8E93',
  },
  timelineLine: {
    width: 2,
    height: 16,
    backgroundColor: '#333',
    marginLeft: 5,
    marginVertical: 2,
  },
  detailChips: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 10,
  },
  receiptList: {
    paddingHorizontal: 4,
    paddingBottom: 6,
  },
  receiptRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
  },
  quotationListAccordionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#2D3033',
    backgroundColor: '#17191B',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
  },
  quotationListAccordionHeaderExpanded: {
    borderColor: '#3C424A',
    backgroundColor: '#1D2023',
  },
  quotationListAccordionTitle: {
    fontSize: 13,
    color: '#D3D7DD',
    fontWeight: '700',
  },
  quotationAccordionRow: {
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
  },
  quotationAccordionRowExpanded: {
    backgroundColor: '#1F2328',
    borderWidth: 1,
    borderColor: '#343A42',
  },
  quotationAccordionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  quoteHeaderLeft: {
    flex: 1,
    marginRight: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  quotationAccordionRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  quotationAccordionBody: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#2D3033',
  },
  quotationDetailTopRow: {
    marginBottom: 8,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  quotationDetailStatusText: {
    fontSize: 11,
    color: '#8E8E93',
    fontWeight: '700',
    letterSpacing: 0.2,
    textTransform: 'uppercase',
  },
  quotationDetailLabel: {
    fontSize: 12,
    color: '#7D838B',
    fontWeight: '500',
  },
  quotationDetailValue: {
    fontSize: 12,
    color: '#B7BDC4',
    fontWeight: '600',
  },
  pendingPill: {
    backgroundColor: '#3A3020',
    borderColor: '#5D4A26',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  pendingPillText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FFD49A',
  },
  receiptItem: {
    fontSize: 14,
    color: '#ccc',
  },
  receiptAmount: {
    fontSize: 14,
    color: '#fff',
    fontWeight: '600',
  },
  pendingItem: {
    backgroundColor: '#2A241B',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#5D4A26',
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 6,
  },
  acceptedItem: {
    paddingVertical: 6,
  },
  receiptDivider: {
    height: 1,
    backgroundColor: '#222426',
    marginVertical: 8,
  },
  receiptTotalLabel: {
    fontSize: 14,
    color: '#8E8E93',
    fontWeight: '600',
  },
  receiptTotalValue: {
    fontSize: 16,
    color: '#fff',
    fontWeight: '800',
  },
  paymentSummaryGrid: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 10,
  },
  paymentSummaryTile: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#2D3033',
    backgroundColor: '#17191B',
    paddingVertical: 9,
    paddingHorizontal: 8,
  },
  progressBarContainer: {
    width: '100%',
    height: 6,
    borderRadius: 999,
    backgroundColor: '#2D3033',
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#34C759',
  },
  progressText: {
    marginTop: 6,
    fontSize: 11,
    fontWeight: '700',
    color: '#A8AFB8',
  },
  receiptYouLabel: {
    fontSize: 13,
    color: '#8E8E93',
    fontWeight: '600',
  },
  receiptYouValue: {
    fontSize: 16,
    color: '#34C759',
    fontWeight: '800',
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  chipDefault: {
    backgroundColor: '#222426',
  },
  chipSuccess: {
    backgroundColor: '#34C75915',
  },
  chipWarning: {
    backgroundColor: '#FFD60A15',
  },
  chipText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#8E8E93',
  },
  noteBox: {
    backgroundColor: '#222426',
    borderRadius: 10,
    padding: 12,
    marginTop: 8,
  },
  noteLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#8E8E93',
    marginBottom: 4,
  },
  noteText: {
    fontSize: 13,
    color: '#ccc',
    lineHeight: 18,
  },
  timerText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FFD60A',
  },
  elapsedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
    paddingHorizontal: 6,
  },
  elapsedLabel: {
    fontSize: 12,
    color: '#8E8E93',
    fontWeight: '600',
  },
  elapsedValue: {
    fontSize: 18,
    color: '#FFD60A',
    fontWeight: '700',
  },
  actionButtonsContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: '#1A1C1E',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    zIndex: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 10,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 18,
    minHeight: 54,
    borderRadius: 12,
    borderWidth: 1,
    justifyContent: 'center',
  },
  actionButtonDisabled: {
    opacity: 0.7,
  },
  actionButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 15,
    marginLeft: 10,
  },
  actionButtonWrapper: {
    width: '48%',
    paddingHorizontal: 6,
    marginBottom: 8,
  },
  actionButtonSmallWrapper: {
    width: '49%',
  },
  fullWidthButtonWrapper: {
    width: '100%',
    marginTop: 8,
  },
  actionButtonLargeWrapper: {
    width: '49%',
  },
  checkboxRowFull: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 10,
    justifyContent: 'flex-start',
    backgroundColor: '#111213',
    borderWidth: 1,
    borderColor: '#232425',
  },
  pendingContainer: {
    width: '100%',
    flexDirection: 'row',
    gap: 8,
    alignItems: 'flex-start',
  },
  pendingLeft: {
    flex: 1,
    paddingRight: 8,
  },
  pendingRight: {
    width: '40%',
  },
  startTravelButton: {
    backgroundColor: '#007AFF',
  },
  startJobButton: {
    backgroundColor: '#FF8C00',
  },
  finishJobButton: {
    backgroundColor: '#34C759',
  },
  pauseButton: {
    backgroundColor: '#8E8E93',
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
    minWidth: 160,
  },
  checkboxChecked: {
    backgroundColor: '#243A1E',
  },
  largePrimaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: '#007AFF',
    borderRadius: 12,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#1259C8',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 3,
  },
  largePrimaryButtonDisabled: {
    backgroundColor: '#3D4D63',
    borderColor: '#334257',
    opacity: 0.78,
  },
  largeSecondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: '#FF3B30',
    borderRadius: 12,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#A92A22',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  arrivedLargeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: '#2D6A4F',
    borderRadius: 12,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#1B4332',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  arrivedLargeButtonDone: {
    backgroundColor: '#243A1E',
    borderColor: '#34C759',
    opacity: 0.95,
  },
  jobRoleBadge: {
    alignSelf: 'flex-start',
    marginTop: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  jobRoleBadgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  checkboxUnchecked: {
    backgroundColor: '#222426',
  },
  resumeButton: {
    backgroundColor: '#007AFF',
  },
  paymentReceivedButton: {
    backgroundColor: '#FFD60A',
  },
  completeButton: {
    backgroundColor: '#34C759',
  },
  cancelButton: {
    backgroundColor: '#FF3B30',
  },
  completionInfo: {
    gap: 10,
  },
  completionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  completionLabel: {
    fontSize: 14,
    color: '#8E8E93',
  },
  completionAmount: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#34C759',
  },
  actionSection: {
    marginTop: 8,
  },
  completeLargeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#34C759',
    borderRadius: 14,
    paddingVertical: 16,
  },
  completeLargeButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
  },
  finishLargeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: '#34C759',
    borderRadius: 12,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#2A2C2E',
  },
  disabledButton: {
    opacity: 0.6,
  },
});
