import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#111214',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 16,
    backgroundColor: '#1A1C1E',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
  },
  locationButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FF8C0015',
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterContainer: {
    backgroundColor: '#1A1C1E',
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  filterChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#222426',
    marginRight: 8,
  },
  filterChipActive: {
    backgroundColor: '#FF8C00',
  },
  filterChipText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#8E8E93',
  },
  filterChipTextActive: {
    color: '#fff',
  },
  mapContainer: {
    height: 280,
    backgroundColor: '#1A1C1E',
    borderBottomWidth: 1,
    borderBottomColor: '#2A2C2E',
    position: 'relative',
  },
  map: {
    flex: 1,
  },
  mapLoadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1A1C1E',
    paddingHorizontal: 20,
  },
  mapLoadingText: {
    marginTop: 12,
    fontSize: 14,
    color: '#8E8E93',
    textAlign: 'center',
  },
  mapErrorCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#161819',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#2A2C2E',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  mapErrorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  mapErrorTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#F4F4F5',
  },
  mapErrorText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#A1A1AA',
  },
  mapRetryButton: {
    marginTop: 10,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FF8C00',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 9,
  },
  mapRetryText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
  },
  mapOverlay: {
    position: 'absolute',
    top: 16,
    right: 16,
  },
  mapStats: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#1E1E1EDD',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
  },
  mapStatsText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#fff',
  },
  myLocationButton: {
    position: 'absolute',
    bottom: 16,
    right: 16,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FF8C00',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  jobListContainer: {
    flex: 1,
    backgroundColor: '#111214',
  },
  jobListHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
  },
  jobListTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  broadcastSwitchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#1A1C1E',
    borderWidth: 1,
    borderColor: '#2A2C2E',
    borderRadius: 999,
    paddingLeft: 10,
    paddingRight: 6,
    paddingVertical: 3,
  },
  broadcastSwitchText: {
    color: '#E0E0E0',
    fontSize: 12,
    fontWeight: '600',
  },
  jobList: {
    flex: 1,
    paddingHorizontal: 20,
  },
  loader: {
    marginTop: 40,
  },
  errorContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
  },
  errorText: {
    fontSize: 16,
    color: '#FF3B30',
    marginTop: 16,
    textAlign: 'center',
  },
  retryButton: {
    marginTop: 16,
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: '#FF8C00',
    borderRadius: 8,
  },
  retryText: {
    color: '#fff',
    fontWeight: '600',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
    marginTop: 40,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#fff',
    marginTop: 16,
  },
  emptySubtext: {
    fontSize: 14,
    color: '#8E8E93',
    marginTop: 8,
    textAlign: 'center',
  },
  jobCard: {
    backgroundColor: '#1A1C1E',
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#2A2C2E',
  },
  jobCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  jobTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#fff',
    flex: 1,
  },
  jobInfo: {
    marginBottom: 10,
  },
  jobInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  jobInfoText: {
    fontSize: 13,
    color: '#8E8E93',
    flex: 1,
  },
  jobCardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#2A2C2E',
  },
  jobEarnings: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#34C759',
  },
  navigateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FF8C00',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
  },
  navigateText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#fff',
  },
  broadcastCard: {
    borderColor: '#34C759',
    borderWidth: 2,
    backgroundColor: '#1A1F1A',
  },
  broadcastDescription: {
    fontSize: 14,
    color: '#E0E0E0',
    marginBottom: 12,
    lineHeight: 20,
  },
  servicesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 12,
  },
  serviceTag: {
    backgroundColor: '#2A2C2E',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#34C75940',
  },
  serviceTagText: {
    fontSize: 11,
    color: '#34C759',
    fontWeight: '600',
  },
  timerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  timerText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#FF8C00',
  },
  acceptButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#34C759',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
  },
  acceptButtonWaiting: {
    backgroundColor: '#FF8C00',
    paddingHorizontal: 12,
  },
  acceptText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#fff',
  },
  urgentBadge: {
    backgroundColor: '#FF3B30',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    marginLeft: 'auto',
  },
  urgentText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#fff',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#1A1C1E',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    height: '85%',
    paddingTop: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#2A2C2E',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
  },
  modalBody: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  modalTimer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#2A2C2E',
    padding: 14,
    borderRadius: 12,
    marginBottom: 20,
  },
  modalTimerText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  modalSection: {
    marginBottom: 20,
  },
  modalSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 12,
  },
  modalText: {
    fontSize: 15,
    color: '#E0E0E0',
    lineHeight: 22,
  },
  modalServiceItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#222426',
    padding: 12,
    borderRadius: 10,
    marginBottom: 8,
  },
  modalServiceInfo: {
    flex: 1,
    marginRight: 12,
  },
  modalServiceName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 4,
  },
  modalServiceDesc: {
    fontSize: 13,
    color: '#8E8E93',
  },
  modalServicePrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#34C759',
  },
  modalConcernImage: {
    width: '100%',
    height: 200,
    borderRadius: 12,
    backgroundColor: '#222426',
    marginTop: 8,
  },
  modalPriceBreakdown: {
    backgroundColor: '#222426',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
  },
  modalPriceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
  },
  modalPriceLabel: {
    fontSize: 14,
    color: '#8E8E93',
  },
  modalPriceValue: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  modalPriceNote: {
    paddingTop: 4,
    borderTopWidth: 1,
    borderTopColor: '#3A3C3E',
    marginTop: 8,
  },
  modalPriceNoteText: {
    fontSize: 12,
    color: '#8E8E93',
    fontStyle: 'italic',
  },
  modalCard: {
    backgroundColor: '#1A1C1E',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#2A2C2E',
    marginBottom: 12,
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  cardTitleText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  routeLoadingWrap: {
    paddingVertical: 8,
    alignItems: 'flex-start',
  },
  cardPrimaryText: {
    fontSize: 15,
    color: '#FFFFFF',
    marginBottom: 8,
  },
  cardSecondaryText: {
    fontSize: 14,
    color: '#8E8E93',
    marginBottom: 6,
  },
  routeErrorText: {
    fontSize: 13,
    color: '#FF3B30',
    marginTop: 4,
  },
  trafficNoteText: {
    fontSize: 12,
    color: '#8E8E93',
    marginTop: 4,
    fontStyle: 'italic',
  },
  cardRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#2A2C2E',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
  },
  cardRowLabel: {
    fontSize: 14,
    color: '#8E8E93',
  },
  cardRowValue: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  cardRowLabelBold: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  cardRowValueBold: {
    fontSize: 16,
    color: '#FF8C00',
    fontWeight: '700',
  },
  cardDivider: {
    borderTopWidth: 1,
    borderTopColor: '#2A2C2E',
    marginVertical: 8,
  },
  rangeText: {
    fontSize: 13,
    color: '#8E8E93',
    marginTop: 2,
  },
  incomeCard: {
    backgroundColor: '#1A1C1E',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#FF8C00',
    marginBottom: 12,
  },
  incomeTitleStyle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  totalStyleLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  totalStyleValue: {
    fontSize: 22,
    fontWeight: '800',
    color: '#34C759',
  },
  disclaimerCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: '#1A1C1E',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#2A2C2E',
    marginBottom: 12,
  },
  disclaimerText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    color: '#8E8E93',
  },
  tokensCard: {
    backgroundColor: '#1A1C1E',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2A2C2E',
    padding: 10,
    marginBottom: 12,
  },
  tokensTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  tokensRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#2A2C2E',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
    marginBottom: 6,
  },
  tokensLabel: {
    fontSize: 12,
    color: '#8E8E93',
  },
  tokensValue: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  tokensWarning: {
    fontSize: 12,
    color: '#FF3B30',
    marginTop: 4,
  },
  modalTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#34C75920',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#34C759',
    marginBottom: 20,
  },
  modalTotalLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  modalTotalValue: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#34C759',
  },
  modalFooter: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#2A2C2E',
  },
  waitingBanner: {
    marginHorizontal: 20,
    marginTop: 14,
    marginBottom: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#FF8C0040',
    backgroundColor: '#FF8C0018',
    padding: 14,
  },
  waitingBannerHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  waitingBannerIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FF8C0020',
  },
  waitingBannerTextWrap: {
    flex: 1,
  },
  waitingBannerTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#fff',
    marginBottom: 4,
  },
  waitingBannerText: {
    fontSize: 12,
    color: '#F1D9C2',
    lineHeight: 18,
  },
  waitingBannerActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
  },
  waitingBannerActionPrimary: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FF8C00',
    paddingVertical: 10,
    borderRadius: 10,
  },
  waitingBannerActionPrimaryText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#fff',
  },
  waitingBannerActionSecondary: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2A2C2E',
    paddingVertical: 10,
    borderRadius: 10,
  },
  waitingBannerActionSecondaryText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#E7E7EA',
  },
  modalAcceptButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#34C759',
    paddingVertical: 16,
    borderRadius: 12,
    marginBottom: 10,
  },
  modalAcceptButtonDisabled: {
    backgroundColor: '#34C75970',
  },
  modalAcceptText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
  },
  modalCancelButton: {
    paddingVertical: 14,
    alignItems: 'center',
  },
  modalCancelText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#8E8E93',
  },
});
