import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1E1E1E',
  },
  header: {
    paddingTop: 54,
    paddingBottom: 16,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#2D2D2D',
    backgroundColor: '#1A1A1A',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#3A3A3A',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#252525',
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  selectModeButton: {
    minWidth: 72,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: '#3A3A3A',
    backgroundColor: '#242424',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 10,
  },
  selectModeButtonText: {
    color: '#D0D5DB',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  loaderWrap: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
  },
  sectionHeaderRow: {
    marginTop: 2,
    marginBottom: 8,
  },
  sectionTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 8,
  },
  itemCard: {
    backgroundColor: '#242424',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#333333',
    padding: 12,
    marginBottom: 12,
  },
  itemSelectableRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  itemCardFlex: {
    flex: 1,
  },
  sideSelectButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#3A3F45',
    backgroundColor: '#1F2226',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  sideSelectButtonActive: {
    borderColor: '#2F6B48',
    backgroundColor: '#1E2A23',
  },
  acceptedItemCard: {
    backgroundColor: '#202224',
    borderColor: '#3F4348',
    opacity: 0.92,
  },
  editingItemCard: {
    borderColor: '#FFB357',
    borderStyle: 'dashed',
    backgroundColor: '#2A261F',
  },
  removedGhostItemCard: {
    opacity: 0.55,
    borderColor: '#6B3B3B',
    backgroundColor: '#2A2020',
  },
  itemAccordionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  itemAccordionBody: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#333333',
    paddingTop: 10,
  },
  itemAccordionTitle: {
    color: '#F3F3F3',
    fontSize: 15,
    fontWeight: '700',
  },
  itemAccordionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  itemAccordionMeta: {
    marginTop: 4,
    color: '#9FA4AA',
    fontSize: 12,
  },
  itemAccordionRight: {
    alignItems: 'flex-end',
    gap: 6,
  },
  itemAccordionTotal: {
    color: '#FFB357',
    fontSize: 14,
    fontWeight: '700',
  },
  acceptedBadge: {
    backgroundColor: '#26322A',
    borderWidth: 1,
    borderColor: '#3A5A40',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  acceptedBadgeText: {
    color: '#9EE6B0',
    fontSize: 11,
    fontWeight: '700',
  },
  pendingBadge: {
    backgroundColor: '#3A3020',
    borderWidth: 1,
    borderColor: '#5D4A26',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  pendingBadgeText: {
    color: '#FFD49A',
    fontSize: 11,
    fontWeight: '700',
  },
  changeTypeBadge: {
    backgroundColor: '#2B2636',
    borderWidth: 1,
    borderColor: '#4B3F67',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  changeTypeBadgeText: {
    color: '#C7B5FF',
    fontSize: 11,
    fontWeight: '700',
  },
  changeTypeBadgeDanger: {
    backgroundColor: '#3A2020',
    borderWidth: 1,
    borderColor: '#6B3B3B',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  changeTypeBadgeDangerText: {
    color: '#FFB4B0',
    fontSize: 11,
    fontWeight: '700',
  },
  itemCardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  itemActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  iconActionButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#4A4E54',
    backgroundColor: '#25282C',
  },
  iconActionButtonDanger: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#5A2C2C',
    backgroundColor: '#2C2121',
  },
  editingPill: {
    backgroundColor: '#3A3020',
    borderWidth: 1,
    borderColor: '#5D4A26',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  editingPillText: {
    color: '#FFD49A',
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  itemLabel: {
    color: '#B8B8B8',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  removeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: '#5E4A2E',
    backgroundColor: '#2F2A22',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  editButtonText: {
    color: '#FFB357',
    fontSize: 12,
    fontWeight: '700',
  },
  removeButtonText: {
    color: '#FF6B6B',
    fontSize: 12,
    fontWeight: '600',
  },
  itemNameInput: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#3A3A3A',
    backgroundColor: '#1F1F1F',
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#FFFFFF',
    fontSize: 14,
    marginBottom: 10,
  },
  itemFieldsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  fieldCol: {
    flex: 1,
  },
  numericInput: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#3A3A3A',
    backgroundColor: '#1F1F1F',
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#FFFFFF',
    fontSize: 14,
  },
  readonlyInput: {
    color: '#8A8F95',
    borderColor: '#35383C',
    backgroundColor: '#1B1D1F',
  },
  itemTotalRow: {
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#333333',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  itemTotalLabel: {
    color: '#A0A0A0',
    fontSize: 13,
    fontWeight: '600',
  },
  itemTotalValue: {
    color: '#FFB357',
    fontSize: 14,
    fontWeight: '700',
  },
  addItemButton: {
    backgroundColor: '#FF8C00',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 2,
    marginBottom: 16,
  },
  addItemButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  addItemButtonSmall: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: '#3A3A3A',
    backgroundColor: '#242424',
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 7,
    marginTop: 2,
    marginBottom: 16,
  },
  addItemButtonSmallText: {
    color: '#D6D6D6',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  stickySelectionBar: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 20,
    zIndex: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#16181B',
    borderWidth: 1,
    borderColor: '#2C2F34',
    borderRadius: 14,
    padding: 10,
  },
  stickySecondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    flex: 1,
    backgroundColor: '#22262B',
    borderWidth: 1,
    borderColor: '#353A40',
    borderRadius: 10,
    paddingVertical: 10,
  },
  stickySecondaryButtonText: {
    color: '#D0D5DB',
    fontSize: 12,
    fontWeight: '700',
  },
  stickyDangerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    flex: 1.3,
    borderWidth: 1,
    borderColor: '#5A2C2C',
    backgroundColor: '#2C2121',
    borderRadius: 10,
    paddingVertical: 10,
  },
  stickyDangerButtonText: {
    color: '#FFB4B0',
    fontSize: 12,
    fontWeight: '800',
  },
  finalToggleRow: {
    backgroundColor: '#242424',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#333333',
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  finalToggleText: {
    color: '#E5E5E5',
    fontSize: 14,
    fontWeight: '600',
  },
  finalToggleIconWrap: {
    padding: 4,
  },
  summaryCard: {
    backgroundColor: '#242424',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#333333',
    padding: 14,
    marginBottom: 16,
  },
  summaryTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 10,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  summaryLabel: {
    color: '#B8B8B8',
    fontSize: 14,
  },
  summaryValue: {
    color: '#E5E5E5',
    fontSize: 14,
    fontWeight: '600',
  },
  summaryDivider: {
    marginVertical: 6,
    borderTopWidth: 1,
    borderTopColor: '#3A3A3A',
  },
  totalLabel: {
    color: '#FFD49A',
    fontSize: 15,
    fontWeight: '700',
  },
  totalValue: {
    color: '#FF8C00',
    fontSize: 18,
    fontWeight: '800',
  },
  saveButton: {
    backgroundColor: '#FF8C00',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  modalBox: {
    width: '100%',
    maxWidth: 420,
    maxHeight: '80%',
    backgroundColor: '#16181B',
    borderWidth: 1,
    borderColor: '#2C2F34',
    borderRadius: 14,
    padding: 16,
  },
  modalTitle: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 6,
  },
  modalText: {
    color: '#B8BCC3',
    fontSize: 13,
    marginBottom: 12,
  },
  modalBreakdownRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 4,
  },
  modalBreakdownLabel: {
    color: '#D6D9DE',
    fontSize: 13,
    fontWeight: '600',
  },
  modalBreakdownValue: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  modalChangeList: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#2C2F34',
    borderBottomWidth: 1,
    borderBottomColor: '#2C2F34',
    paddingVertical: 8,
    maxHeight: 220,
  },
  modalChangeItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 5,
  },
  modalChangeItemBlock: {
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#24282D',
  },
  modalChangeItemText: {
    flex: 1,
    color: '#E7E9ED',
    fontSize: 13,
  },
  modalChangeSubText: {
    color: '#9FA5AD',
    fontSize: 12,
    marginLeft: 4,
    marginBottom: 2,
  },
  modalChangeTypeAdd: {
    fontSize: 10,
    color: '#1D3A24',
    fontWeight: '800',
    backgroundColor: '#8CE99A',
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  modalChangeTypeEdit: {
    fontSize: 10,
    color: '#5A3D0A',
    fontWeight: '800',
    backgroundColor: '#FFD49A',
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  modalChangeTypeDelete: {
    fontSize: 10,
    color: '#631B21',
    fontWeight: '800',
    backgroundColor: '#FFB4B0',
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  modalActionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 14,
  },
  modalBtnSecondary: {
    backgroundColor: '#22262B',
    borderWidth: 1,
    borderColor: '#353A40',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minWidth: 90,
    alignItems: 'center',
  },
  modalBtnSecondaryText: {
    color: '#D0D5DB',
    fontWeight: '700',
  },
  modalBtnPrimary: {
    backgroundColor: '#FF8C00',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minWidth: 110,
    alignItems: 'center',
  },
  modalBtnPrimaryText: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
});
