import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1E1E1E',
  },
  header: {
    paddingTop: 54,
    paddingBottom: 16,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#2D2D2D',
    backgroundColor: '#1A1A1A',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#3A3A3A',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#252525',
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  selectModeButton: {
    minWidth: 72,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: '#3A3A3A',
    backgroundColor: '#242424',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 10,
  },
  selectModeButtonText: {
    color: '#D0D5DB',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  loaderWrap: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
  },
  sectionHeaderRow: {
    marginTop: 2,
    marginBottom: 8,
  },
  sectionTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 8,
  },
  itemCard: {
    backgroundColor: '#242424',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#333333',
    padding: 12,
    marginBottom: 12,
    position: 'relative',
  },
  itemSelectableRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  itemCardFlex: {
    flex: 1,
  },
  sideSelectButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#3A3F45',
    backgroundColor: '#1F2226',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  sideSelectButtonActive: {
    borderColor: '#2F6B48',
    backgroundColor: '#1E2A23',
  },
  quickRemoveOverlayButton: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#5A2C2C',
    backgroundColor: '#2C2121',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: 6,
    right: 6,
    zIndex: 4,
  },
  acceptedItemCard: {
    backgroundColor: '#202224',
    borderColor: '#3F4348',
    opacity: 0.92,
  },
  editingItemCard: {
    borderColor: '#FFB357',
    borderStyle: 'dashed',
    backgroundColor: '#2A261F',
  },
  removedGhostItemCard: {
    opacity: 0.55,
    borderColor: '#6B3B3B',
    backgroundColor: '#2A2020',
  },
  itemAccordionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  accordionIconWrap: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  itemAccordionLeftBlock: {
    flex: 1,
    minWidth: 0,
  },
  itemAccordionHeaderWithQuickRemove: {
    paddingRight: 18,
  },
  itemAccordionBody: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#333333',
    paddingTop: 10,
  },
  itemAccordionTitle: {
    color: '#F3F3F3',
    fontSize: 14,
    fontWeight: '700',
    flexShrink: 1,
  },
  itemAccordionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minWidth: 0,
  },
  itemAccordionBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
    marginTop: 4,
  },
  itemAccordionMeta: {
    marginTop: 4,
    color: '#9FA4AA',
    fontSize: 12,
  },
  itemAccordionRight: {
    alignItems: 'flex-end',
    gap: 6,
    flexShrink: 0,
  },
  itemAccordionTotal: {
    color: '#FFB357',
    fontSize: 14,
    fontWeight: '700',
  },
  acceptedBadge: {
    backgroundColor: '#26322A',
    borderWidth: 1,
    borderColor: '#3A5A40',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  acceptedBadgeText: {
    color: '#9EE6B0',
    fontSize: 11,
    fontWeight: '700',
  },
  pendingBadge: {
    backgroundColor: '#3A3020',
    borderWidth: 1,
    borderColor: '#5D4A26',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  pendingBadgeText: {
    color: '#FFD49A',
    fontSize: 11,
    fontWeight: '700',
  },
  changeTypeBadge: {
    backgroundColor: '#2B2636',
    borderWidth: 1,
    borderColor: '#4B3F67',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  changeTypeBadgeText: {
    color: '#C7B5FF',
    fontSize: 11,
    fontWeight: '700',
  },
  changeTypeBadgeDanger: {
    backgroundColor: '#3A2020',
    borderWidth: 1,
    borderColor: '#6B3B3B',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  changeTypeBadgeDangerText: {
    color: '#FFB4B0',
    fontSize: 11,
    fontWeight: '700',
  },
  itemCardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  itemActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  iconActionButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#4A4E54',
    backgroundColor: '#25282C',
  },
  iconActionButtonDanger: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#5A2C2C',
    backgroundColor: '#2C2121',
  },
  editingPill: {
    backgroundColor: '#3A3020',
    borderWidth: 1,
    borderColor: '#5D4A26',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  editingPillText: {
    color: '#FFD49A',
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  itemLabel: {
    color: '#B8B8B8',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  removeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: '#5E4A2E',
    backgroundColor: '#2F2A22',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  editButtonText: {
    color: '#FFB357',
    fontSize: 12,
    fontWeight: '700',
  },
  removeButtonText: {
    color: '#FF6B6B',
    fontSize: 12,
    fontWeight: '600',
  },
  itemNameInput: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#3A3A3A',
    backgroundColor: '#1F1F1F',
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#FFFFFF',
    fontSize: 14,
    marginBottom: 10,
  },
  itemFieldsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  fieldCol: {
    flex: 1,
  },
  numericInput: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#3A3A3A',
    backgroundColor: '#1F1F1F',
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#FFFFFF',
    fontSize: 14,
  },
  readonlyInput: {
    color: '#8A8F95',
    borderColor: '#35383C',
    backgroundColor: '#1B1D1F',
  },
  itemTotalRow: {
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#333333',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  itemTotalLabel: {
    color: '#A0A0A0',
    fontSize: 13,
    fontWeight: '600',
  },
  itemTotalValue: {
    color: '#FFB357',
    fontSize: 14,
    fontWeight: '700',
  },
  addItemButton: {
    backgroundColor: '#FF8C00',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 2,
    marginBottom: 16,
  },
  addItemButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  addLineButtonsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 2,
    marginBottom: 16,
  },
  addItemButtonSmall: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: '#3A3A3A',
    backgroundColor: '#242424',
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  addServiceButtonSmall: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: '#2F4D3D',
    backgroundColor: '#1E2622',
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  addItemButtonSmallText: {
    color: '#D6D6D6',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  addServiceButtonSmallText: {
    color: '#9ECFB0',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  addFromCatalogButton: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: '#2F4D3D',
    backgroundColor: '#1A221C',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 16,
  },
  addFromCatalogButtonText: {
    color: '#9ECFB0',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  catalogModalBox: {
    width: '100%',
    maxWidth: 420,
    maxHeight: '85%',
    backgroundColor: '#16181B',
    borderWidth: 1,
    borderColor: '#2C2F34',
    borderRadius: 14,
    padding: 16,
  },
  catalogSearchInput: {
    backgroundColor: '#22262B',
    borderWidth: 1,
    borderColor: '#353A40',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#E7E9ED',
    fontSize: 14,
    marginBottom: 8,
  },
  catalogCenterBlock: {
    minHeight: 120,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 24,
  },
  catalogErrorText: {
    color: '#FF8A8A',
    fontSize: 14,
    textAlign: 'center',
    paddingHorizontal: 8,
  },
  catalogList: {
    maxHeight: 340,
    marginBottom: 8,
  },
  catalogListEmpty: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingVertical: 20,
  },
  catalogEmptyHint: {
    color: '#9FA5AD',
    fontSize: 13,
    textAlign: 'center',
    paddingHorizontal: 12,
  },
  catalogRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#2C2F34',
  },
  catalogRowLeft: {
    flex: 1,
    paddingRight: 10,
  },
  catalogRowTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  catalogRowSub: {
    color: '#8E9399',
    fontSize: 12,
    marginTop: 4,
  },
  catalogRowPrice: {
    color: '#FFB357',
    fontSize: 14,
    fontWeight: '700',
  },
  catalogCloseButton: {
    alignSelf: 'center',
    marginTop: 4,
    paddingVertical: 10,
    paddingHorizontal: 28,
    backgroundColor: '#22262B',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#353A40',
  },
  catalogCloseButtonText: {
    color: '#D0D5DB',
    fontSize: 14,
    fontWeight: '700',
  },
  catalogBackRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 10,
    alignSelf: 'flex-start',
  },
  catalogBackText: {
    color: '#9ECFB0',
    fontSize: 13,
    fontWeight: '700',
  },
  catalogAddonPickRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#2C2F34',
  },
  catalogAddonPickMid: {
    flex: 1,
    minWidth: 0,
  },
  catalogFormatHint: {
    color: '#6B7078',
    fontSize: 11,
    marginTop: 4,
    fontStyle: 'italic',
  },
  catalogAddonActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
    marginTop: 12,
  },
  catalogSecondaryButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    backgroundColor: '#22262B',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#353A40',
  },
  catalogSecondaryButtonText: {
    color: '#D0D5DB',
    fontSize: 14,
    fontWeight: '700',
  },
  catalogConfirmButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    backgroundColor: '#2F4D3D',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#4A7C5F',
  },
  catalogConfirmButtonText: {
    color: '#E8F8ED',
    fontSize: 14,
    fontWeight: '800',
  },
  catalogInlineErrorBox: {
    marginBottom: 10,
    padding: 10,
    backgroundColor: 'rgba(255,138,138,0.08)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,138,138,0.25)',
  },
  catalogSkipAddonsButton: {
    marginTop: 10,
    alignSelf: 'stretch',
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: '#2A2E33',
  },
  catalogSkipAddonsButtonText: {
    color: '#9ECFB0',
    fontSize: 13,
    fontWeight: '700',
  },
  catalogLoadingSub: {
    marginTop: 10,
    color: '#9FA5AD',
    fontSize: 13,
  },
  addonLineBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,179,87,0.35)',
    backgroundColor: 'rgba(255,179,87,0.12)',
  },
  addonLineBadgeText: {
    color: '#FFB357',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  stickySelectionBar: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 20,
    zIndex: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#16181B',
    borderWidth: 1,
    borderColor: '#2C2F34',
    borderRadius: 14,
    padding: 10,
  },
  stickySecondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    flex: 1,
    backgroundColor: '#22262B',
    borderWidth: 1,
    borderColor: '#353A40',
    borderRadius: 10,
    paddingVertical: 10,
  },
  stickySecondaryButtonText: {
    color: '#D0D5DB',
    fontSize: 12,
    fontWeight: '700',
  },
  stickyDangerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    flex: 1.3,
    borderWidth: 1,
    borderColor: '#5A2C2C',
    backgroundColor: '#2C2121',
    borderRadius: 10,
    paddingVertical: 10,
  },
  stickyDangerButtonText: {
    color: '#FFB4B0',
    fontSize: 12,
    fontWeight: '800',
  },
  finalToggleRow: {
    backgroundColor: '#242424',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#333333',
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  finalToggleText: {
    color: '#E5E5E5',
    fontSize: 14,
    fontWeight: '600',
  },
  finalToggleIconWrap: {
    padding: 4,
  },
  summaryCard: {
    backgroundColor: '#242424',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#333333',
    padding: 14,
    marginBottom: 16,
  },
  summaryTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 10,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  summaryLabel: {
    color: '#B8B8B8',
    fontSize: 14,
  },
  summaryValue: {
    color: '#E5E5E5',
    fontSize: 14,
    fontWeight: '600',
  },
  summaryDivider: {
    marginVertical: 6,
    borderTopWidth: 1,
    borderTopColor: '#3A3A3A',
  },
  totalLabel: {
    color: '#FFD49A',
    fontSize: 15,
    fontWeight: '700',
  },
  totalValue: {
    color: '#FF8C00',
    fontSize: 18,
    fontWeight: '800',
  },
  saveButton: {
    backgroundColor: '#FF8C00',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  saveButtonDisabled: {
    backgroundColor: '#555555',
    opacity: 0.7,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  modalBox: {
    width: '100%',
    maxWidth: 420,
    maxHeight: '80%',
    backgroundColor: '#16181B',
    borderWidth: 1,
    borderColor: '#2C2F34',
    borderRadius: 14,
    padding: 16,
  },
  modalTitle: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 6,
  },
  modalText: {
    color: '#B8BCC3',
    fontSize: 13,
    marginBottom: 12,
  },
  modalBreakdownRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 4,
  },
  modalBreakdownLabel: {
    color: '#D6D9DE',
    fontSize: 13,
    fontWeight: '600',
  },
  modalBreakdownValue: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  modalChangeList: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#2C2F34',
    borderBottomWidth: 1,
    borderBottomColor: '#2C2F34',
    paddingVertical: 8,
    maxHeight: 220,
  },
  modalChangeItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 5,
  },
  modalChangeItemBlock: {
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#24282D',
  },
  modalChangeItemText: {
    flex: 1,
    color: '#E7E9ED',
    fontSize: 13,
  },
  modalChangeSubText: {
    color: '#9FA5AD',
    fontSize: 12,
    marginLeft: 4,
    marginBottom: 2,
  },
  modalChangeTypeAdd: {
    fontSize: 10,
    color: '#1D3A24',
    fontWeight: '800',
    backgroundColor: '#8CE99A',
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  modalChangeTypeEdit: {
    fontSize: 10,
    color: '#5A3D0A',
    fontWeight: '800',
    backgroundColor: '#FFD49A',
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  modalChangeTypeDelete: {
    fontSize: 10,
    color: '#631B21',
    fontWeight: '800',
    backgroundColor: '#FFB4B0',
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  modalActionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 14,
  },
  modalBtnSecondary: {
    backgroundColor: '#22262B',
    borderWidth: 1,
    borderColor: '#353A40',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minWidth: 90,
    alignItems: 'center',
  },
  modalBtnSecondaryText: {
    color: '#D0D5DB',
    fontWeight: '700',
  },
  modalBtnPrimary: {
    backgroundColor: '#FF8C00',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minWidth: 110,
    alignItems: 'center',
  },
  modalBtnPrimaryText: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  lineKindBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#2A3140',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
    marginBottom: 8,
  },
  lineKindBadgeService: {
    backgroundColor: '#1E3A2F',
  },
  lineKindBadgeText: {
    color: '#9ECFB0',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  sourceChipsWrap: {
    marginTop: 10,
  },
  sourceChipsLabel: {
    color: '#AFAFAF',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 8,
  },
  sourceChipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  sourceChip: {
    borderWidth: 1,
    borderColor: '#3A3A3A',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: '#1E1E1E',
  },
  sourceChipActive: {
    borderColor: '#FF8C00',
    backgroundColor: '#2A2418',
  },
  sourceChipText: {
    color: '#C9CDD2',
    fontSize: 11,
    fontWeight: '600',
  },
  sourceChipTextActive: {
    color: '#FFB357',
  },
  receiptRowWrap: {
    marginTop: 10,
  },
  receiptPreviewWrap: {
    marginTop: 12,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2C3036',
    backgroundColor: '#121418',
  },
  receiptPreviewLabel: {
    color: '#B8BCC3',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  receiptPreviewImage: {
    width: '100%',
    maxHeight: 240,
    minHeight: 120,
    borderRadius: 10,
    backgroundColor: '#0A0C0F',
  },
  receiptPreviewPendingNote: {
    marginTop: 10,
    color: '#8E9399',
    fontSize: 12,
    lineHeight: 17,
  },
  receiptRemovePhotoBtn: {
    marginTop: 10,
    alignSelf: 'flex-start',
    paddingVertical: 6,
  },
  receiptButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#2F6B48',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  receiptButtonDisabled: {
    backgroundColor: '#3A3A3A',
  },
  receiptButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  receiptHelpTitle: {
    color: '#D6D9DE',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 6,
  },
  receiptClearLink: {
    color: '#FF8A8A',
    fontSize: 12,
    fontWeight: '700',
  },
  receiptHintText: {
    color: '#9CA3AF',
    fontSize: 11,
    marginTop: 6,
  },
  receiptSourceModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.72)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 22,
  },
  receiptSourceModalCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#16181B',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#2C3036',
    paddingTop: 18,
    paddingHorizontal: 18,
    paddingBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 12,
  },
  receiptSourceModalHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  receiptSourceModalTitle: {
    flex: 1,
    paddingRight: 12,
    color: '#F2F4F7',
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  receiptSourceModalCloseHit: {
    padding: 4,
    marginTop: -2,
  },
  receiptSourceModalSubtitle: {
    color: '#8E9399',
    fontSize: 13,
    lineHeight: 19,
    marginBottom: 18,
  },
  receiptSourceOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginBottom: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2F343A',
    backgroundColor: '#1C2026',
  },
  receiptSourceOptionIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  receiptSourceOptionIconWrapCamera: {
    backgroundColor: 'rgba(255,179,87,0.12)',
    borderColor: 'rgba(255,179,87,0.35)',
  },
  receiptSourceOptionIconWrapGallery: {
    backgroundColor: 'rgba(111,226,157,0.12)',
    borderColor: 'rgba(111,226,157,0.3)',
  },
  receiptSourceOptionTextCol: {
    flex: 1,
    minWidth: 0,
  },
  receiptSourceOptionTitle: {
    color: '#E7E9ED',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 3,
  },
  receiptSourceOptionDesc: {
    color: '#7A8088',
    fontSize: 12,
    lineHeight: 16,
  },
  receiptSourceCancelBtn: {
    marginTop: 6,
    alignItems: 'center',
    paddingVertical: 12,
  },
  receiptSourceCancelBtnText: {
    color: '#9FA5AD',
    fontSize: 15,
    fontWeight: '700',
  },
});
