# Generated by Django 6.0.1 on 2026-03-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='booking_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
