import { Platform, StatusBar, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#111214',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#111214',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 14,
    color: '#8E8E93',
  },
  loadingNoticeCard: {
    marginTop: 16,
    width: '86%',
    backgroundColor: '#1A1C1E',
    borderWidth: 1,
    borderColor: '#2A2C2E',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  loadingNoticeTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  loadingNoticeText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#AAB1BB',
    marginBottom: 10,
  },
  loadingNoticeButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#FF8C00',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  loadingNoticeButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  topBar: {
    paddingTop: Platform.OS === 'ios' ? 56 : (StatusBar.currentHeight || 0) + 12,
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: '#1A1C1E',
    borderBottomWidth: 1,
    borderBottomColor: '#2A2C2E',
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  closeButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#2A2C2E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  spacer: {
    width: 34,
    height: 34,
  },
  addressText: {
    fontSize: 13,
    color: '#AAB1BB',
    lineHeight: 18,
  },
  mapWrap: {
    position: 'relative',
    overflow: 'hidden',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  centerPinWrap: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginLeft: -11,
    marginTop: -11,
    zIndex: 6,
  },
  centerPinDot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    backgroundColor: 'rgba(255, 140, 0, 0.9)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  centerPinInner: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#FFFFFF',
  },
  locateButton: {
    position: 'absolute',
    right: 14,
    bottom: 14,
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#1A1C1E',
    borderWidth: 1,
    borderColor: '#2A2C2E',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 7,
  },
  bottomSheet: {
    backgroundColor: '#1A1C1E',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderTopWidth: 1,
    borderTopColor: '#2A2C2E',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 0,
  },
  bottomSheetContent: {
    paddingBottom: 0,
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  optionTextWrap: {
    flex: 1,
    paddingRight: 10,
  },
  optionTitle: {
    fontSize: 17,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  optionSubtitle: {
    marginTop: 2,
    fontSize: 13,
    color: '#8E8E93',
  },
  radioOuter: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 2,
    borderColor: '#8E8E93',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  radioOuterSelected: {
    borderColor: '#FF8C00',
  },
  radioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#FF8C00',
  },
  sliderWrap: {
    marginTop: 6,
    marginBottom: 10,
  },
  sliderRangeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: -6,
  },
  sliderRangeText: {
    fontSize: 12,
    color: '#8E8E93',
  },
  kmInputWrap: {
    backgroundColor: '#1A1C1E',
    borderWidth: 1,
    borderColor: '#2F3338',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingTop: 6,
    paddingBottom: 6,
  },
  kmLabel: {
    fontSize: 11,
    color: '#8E8E93',
    marginBottom: 3,
  },
  kmInput: {
    fontSize: 18,
    color: '#FFFFFF',
    fontWeight: '600',
    paddingVertical: 0,
  },
  inlineError: {
    marginTop: 6,
    fontSize: 12,
    color: '#FF5A55',
  },
  confirmButton: {
    marginTop: 10,
    backgroundColor: '#FF8C00',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  confirmButtonDisabled: {
    opacity: 0.5,
  },
  confirmButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  // Dummy Search Bar (clickable header)
  dummySearchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A1C1E',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#3A3A3C',
    marginTop: 8,
  },
  dummySearchIcon: {
    marginRight: 10,
  },
  dummySearchText: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 15,
  },
});
