import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#111214',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 60,
    paddingBottom: 16,
    backgroundColor: '#1A1C1E',
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FF8C0015',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
  },
  subtitle: {
    fontSize: 13,
    color: '#8E8E93',
    marginBottom: 20,
  },
  // Section
  section: {
    marginBottom: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#fff',
  },
  pickerContainer: {
    backgroundColor: '#1A1C1E',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2A2C2E',
    overflow: 'hidden',
  },
  picker: {
    color: '#fff',
    backgroundColor: 'transparent',
  },
  radiusRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
  },
  radiusChip: {
    width: '31%',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#2A2C2E',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#1A1C1E',
    alignItems: 'center',
  },
  radiusChipSelected: {
    backgroundColor: '#FF8C00',
    borderColor: '#FF8C00',
  },
  radiusChipText: {
    color: '#A8ADB8',
    fontSize: 13,
    fontWeight: '600',
  },
  radiusChipTextSelected: {
    color: '#fff',
  },
  radiusHint: {
    marginTop: 10,
    fontSize: 12,
    color: '#8E8E93',
  },
  // Services grid
  servicesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  serviceCard: {
    backgroundColor: '#1A1C1E',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2A2C2E',
    minWidth: '45%',
    flexGrow: 1,
    position: 'relative',
  },
  serviceCardSelected: {
    backgroundColor: '#FF8C0018',
    borderColor: '#FF8C00',
  },
  serviceCheck: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#FF8C00',
    justifyContent: 'center',
    alignItems: 'center',
  },
  serviceText: {
    fontSize: 14,
    color: '#ccc',
    marginBottom: 4,
  },
  serviceTextSelected: {
    color: '#fff',
    fontWeight: '600',
  },
  servicePrice: {
    fontSize: 12,
    color: '#8E8E93',
    fontWeight: '500',
  },
  servicePriceSelected: {
    color: '#FF8C00',
    fontWeight: '600',
  },
  priceBreakdown: {
    backgroundColor: '#FF8C0010',
    padding: 12,
    borderRadius: 10,
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#FF8C0030',
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  priceBreakdownText: {
    fontSize: 14,
    color: '#FF8C00',
    fontWeight: '600',
  },
  priceNote: {
    fontSize: 11,
    color: '#8E8E93',
    fontStyle: 'italic',
    marginLeft: 18,
  },
  // Text area
  textArea: {
    backgroundColor: '#1A1C1E',
    borderRadius: 12,
    padding: 14,
    fontSize: 14,
    color: '#fff',
    borderWidth: 1,
    borderColor: '#2A2C2E',
    minHeight: 100,
  },
  // Image buttons
  imageRow: {
    flexDirection: 'row',
    gap: 10,
  },
  imageBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#1A1C1E',
    borderRadius: 12,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#2A2C2E',
  },
  imageBtnText: {
    fontSize: 14,
    color: '#FF8C00',
    fontWeight: '600',
  },
  previewContainer: {
    marginTop: 12,
    borderRadius: 12,
    overflow: 'hidden',
  },
  previewImage: {
    width: '100%',
    height: 200,
    borderRadius: 12,
  },
  removeImageBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
  },
  removeImageText: {
    color: '#FF3B30',
    fontSize: 13,
    fontWeight: '600',
  },
  // Location
  locationCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#1A1C1E',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: '#FF8C00',
    gap: 12,
    marginBottom: 10,
  },
  locationIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#FF8C0015',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
  },
  locationTextWrap: {
    flex: 1,
  },
  locationAddress: {
    fontSize: 14,
    color: '#fff',
    fontWeight: '600',
    marginBottom: 3,
  },
  locationDetails: {
    fontSize: 12,
    color: '#8E8E93',
  },
  changeLocationBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#FF8C00',
    borderRadius: 10,
    paddingVertical: 12,
  },
  changeLocationText: {
    fontSize: 14,
    color: '#fff',
    fontWeight: '600',
  },
  selectLocationBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A1C1E',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#2A2C2E',
    gap: 12,
  },
  selectLocationText: {
    flex: 1,
    fontSize: 14,
    color: '#8E8E93',
  },
  input: {
    backgroundColor: '#1A1C1E',
    borderRadius: 12,
    padding: 14,
    fontSize: 14,
    color: '#fff',
    borderWidth: 1,
    borderColor: '#2A2C2E',
  },
  nearbySection: {
    marginTop: 12,
  },
  nearbySubtitle: {
    fontSize: 12,
    color: '#8E8E93',
    marginTop: -2,
    marginBottom: 10,
  },
  nearbyScrollContent: {
    paddingRight: 2,
  },
  nearbyChip: {
    width: 170,
    backgroundColor: '#1A1C1E',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2A2C2E',
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginRight: 8,
  },
  nearbyChipSkeleton: {
    borderColor: '#2A2C2E',
  },
  nearbyHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  nearbyTypeIconWrap: {
    width: 26,
    height: 26,
    borderRadius: 13,
    marginRight: 8,
    backgroundColor: '#FF8C0015',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#FF8C0030',
  },
  nearbyName: {
    fontSize: 12,
    fontWeight: '700',
    color: '#fff',
    marginBottom: 4,
  },
  nearbyMeta: {
    fontSize: 11,
    color: '#8E8E93',
    marginBottom: 7,
  },
  nearbyStatRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 3,
  },
  nearbyStatText: {
    fontSize: 11,
    color: '#D6D6D8',
  },
  nearbyEmptyWrap: {
    backgroundColor: '#1A1C1E',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2A2C2E',
    paddingVertical: 12,
    paddingHorizontal: 12,
  },
  nearbyEmptyText: {
    fontSize: 12,
    color: '#8E8E93',
  },
  nearbyIconSkeleton: {
    width: 26,
    height: 26,
    borderRadius: 13,
    marginBottom: 8,
    backgroundColor: '#2A2C2E',
  },
  nearbyLineLg: {
    height: 10,
    borderRadius: 5,
    backgroundColor: '#2A2C2E',
    marginBottom: 6,
    width: '82%',
  },
  nearbyLineMd: {
    height: 9,
    borderRadius: 5,
    backgroundColor: '#2A2C2E',
    marginBottom: 8,
    width: '72%',
  },
  nearbyLineSm: {
    height: 8,
    borderRadius: 5,
    backgroundColor: '#2A2C2E',
    width: '64%',
  },
  // Submit
  sendBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#FF8C00',
    borderRadius: 14,
    paddingVertical: 16,
    marginTop: 8,
  },
  sendBtnDisabled: {
    opacity: 0.5,
  },
  sendBtnText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
  },
});
