import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0F1113',
  },
  map: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#0F1113',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 15,
    color: '#AAB1BB',
  },
  addressContainer: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 58 : 36,
    left: 14,
    right: 14,
    backgroundColor: '#1A1C1E',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2A2C2E',
    paddingVertical: 12,
    paddingHorizontal: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.28,
    shadowRadius: 4,
    elevation: 5,
  },
  addressText: {
    fontSize: 13,
    color: '#E7EAEE',
    textAlign: 'center',
    lineHeight: 18,
    fontWeight: '600',
  },
  locateButton: {
    position: 'absolute',
    right: 16,
    bottom: 174,
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#1A1C1E',
    borderWidth: 1,
    borderColor: '#2A2C2E',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.35,
    shadowRadius: 5,
    elevation: 7,
  },
  bottomContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#101214',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderTopWidth: 1,
    borderColor: '#2A2C2E',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: Platform.OS === 'ios' ? 28 : 16,
  },
  instructionText: {
    fontSize: 13,
    color: '#AAB1BB',
    textAlign: 'center',
    marginBottom: 12,
    fontWeight: '500',
  },
  buttonContainer: {
    flexDirection: 'row',
    gap: 10,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: '#1A1C1E',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#2A2C2E',
    alignItems: 'center',
    paddingVertical: 12,
  },
  cancelButtonText: {
    fontSize: 15,
    color: '#C7CED8',
    fontWeight: '600',
  },
  confirmButton: {
    flex: 1.5,
    backgroundColor: '#FF8C00',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  confirmButtonDisabled: {
    opacity: 0.45,
  },
  confirmButtonText: {
    fontSize: 15,
    color: '#FFFFFF',
    fontWeight: '700',
  },
});