import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#111214' },
  headerContainer: {
    backgroundColor: '#1A1C1E',
    paddingTop: 60,
    paddingBottom: 20,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  headerLeft: { flex: 1 },
  greeting: { fontSize: 14, color: '#8E8E93', fontWeight: '500' },
  clientName: { fontSize: 22, fontWeight: 'bold', color: '#fff', marginTop: 2 },
  notificationButton: { position: 'relative' },
  notifCircle: {
    width: 44, height: 44, borderRadius: 22,
    backgroundColor: '#2A2C2E', justifyContent: 'center', alignItems: 'center',
  },
  badge: {
    position: 'absolute', top: -2, right: -2,
    backgroundColor: '#FF3B30', borderRadius: 10,
    minWidth: 20, height: 20,
    justifyContent: 'center', alignItems: 'center',
    borderWidth: 2, borderColor: '#1A1C1E',
  },
  badgeText: { fontSize: 10, fontWeight: 'bold', color: '#fff' },
  quickStatsRow: {
    flexDirection: 'row', backgroundColor: '#222426',
    borderRadius: 16, padding: 16, alignItems: 'center',
  },
  quickStat: { flex: 1, alignItems: 'center' },
  quickStatIcon: {
    width: 36, height: 36, borderRadius: 12,
    justifyContent: 'center', alignItems: 'center', marginBottom: 6,
  },
  quickStatValue: { fontSize: 20, fontWeight: 'bold', color: '#fff' },
  quickStatLabel: { fontSize: 11, color: '#8E8E93', marginTop: 2 },
  quickStatDivider: { width: 1, height: 40, backgroundColor: '#333' },
  scrollView: { flex: 1 },
  scrollContent: { paddingTop: 16 },
  loader: { marginTop: 40 },
  errorContainer: { alignItems: 'center', justifyContent: 'center', padding: 40 },
  errorText: { fontSize: 16, color: '#FF3B30', marginTop: 16, textAlign: 'center' },
  retryButton: {
    marginTop: 16, paddingHorizontal: 24, paddingVertical: 12,
    backgroundColor: '#FF8C00', borderRadius: 10,
  },
  retryText: { color: '#fff', fontWeight: '600' },
  section: { paddingHorizontal: 20, marginBottom: 24 },
  sectionHeader: {
    flexDirection: 'row', justifyContent: 'space-between',
    alignItems: 'center', marginBottom: 14,
  },
  sectionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  sectionDot: { width: 8, height: 8, borderRadius: 4 },
  sectionTitle: { fontSize: 17, fontWeight: '700', color: '#fff' },
  seeAll: { fontSize: 13, color: '#FF8C00', fontWeight: '600' },
  jobCard: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: '#1A1C1E', borderRadius: 14, padding: 14,
    marginBottom: 10, borderWidth: 1, borderColor: '#2A2C2E',
  },
  jobCardLeft: { marginRight: 12 },
  jobIconCircle: {
    width: 44, height: 44, borderRadius: 14,
    justifyContent: 'center', alignItems: 'center',
  },
  jobCardCenter: { flex: 1 },
  jobCardTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 4 },
  jobTitle: { fontSize: 15, fontWeight: '600', color: '#fff', flex: 1 },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  jobInfoRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 2 },
  jobInfoText: { fontSize: 12, color: '#8E8E93', flex: 1 },
  jobCardRight: { alignItems: 'flex-end', marginLeft: 8, gap: 8 },
  jobAmount: { fontSize: 15, fontWeight: 'bold', color: '#34C759' },
  requestCard: {
    backgroundColor: '#1A1C1E', borderRadius: 14, padding: 16,
    marginBottom: 10, borderWidth: 1, borderColor: '#2A2C2E',
  },
  requestCardTop: {
    flexDirection: 'row', justifyContent: 'space-between',
    alignItems: 'center', marginBottom: 8,
  },
  requestTypeBadge: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8,
    backgroundColor: '#222426',
  },
  requestTypeText: { fontSize: 12, fontWeight: '700' },
  requestTime: { fontSize: 12, color: '#8E8E93' },
  requestDescription: { fontSize: 13, color: '#8E8E93', lineHeight: 18, marginBottom: 10 },
  requestInfoRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 4,
  },
  requestInfoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flex: 1,
    minWidth: '45%',
  },
  requestInfoLabel: {
    fontSize: 11,
    color: '#8E8E93',
    flex: 1,
  },
  requestPriceText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#34C759',
  },
  quickActionsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  quickActionCard: {
    width: (width - 50) / 2,
    backgroundColor: '#1A1C1E', borderRadius: 14, padding: 18,
    alignItems: 'center', borderWidth: 1, borderColor: '#2A2C2E',
  },
  quickActionIcon: {
    width: 48, height: 48, borderRadius: 16,
    justifyContent: 'center', alignItems: 'center', marginBottom: 10,
  },
  quickActionLabel: { fontSize: 13, fontWeight: '600', color: '#ccc' },
  emptyCard: {
    backgroundColor: '#1A1C1E', borderRadius: 14, padding: 32,
    alignItems: 'center', borderWidth: 1, borderColor: '#2A2C2E',
  },
  emptyTitle: { fontSize: 15, fontWeight: '600', color: '#888', marginTop: 12 },
  emptySubtext: { fontSize: 12, color: '#555', marginTop: 4 },
});
