import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#111214' },
  headerContainer: {
    backgroundColor: '#1A1C1E',
    paddingTop: 60,
    paddingBottom: 20,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  headerLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginRight: 12,
  },
  profileCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#2A2C2E',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#34363A',
    overflow: 'hidden',
  },
  profileImage: {
    width: '100%',
    height: '100%',
  },
  greeting: { fontSize: 14, color: '#8E8E93', fontWeight: '500' },
  clientName: { fontSize: 22, fontWeight: 'bold', color: '#fff', marginTop: 2 },
  notificationButton: { position: 'relative' },
  notifCircle: {
    width: 44, height: 44, borderRadius: 22,
    backgroundColor: '#2A2C2E', justifyContent: 'center', alignItems: 'center',
  },
  badge: {
    position: 'absolute', top: -2, right: -2,
    backgroundColor: '#FF3B30', borderRadius: 10,
    minWidth: 20, height: 20,
    justifyContent: 'center', alignItems: 'center',
    borderWidth: 2, borderColor: '#1A1C1E',
  },
  badgeText: { fontSize: 10, fontWeight: 'bold', color: '#fff' },
  quickStatsRow: {
    flexDirection: 'row', backgroundColor: '#222426',
    borderRadius: 16, padding: 16, alignItems: 'center',
  },
  quickStat: { flex: 1, alignItems: 'center' },
  quickStatIcon: {
    width: 36, height: 36, borderRadius: 12,
    justifyContent: 'center', alignItems: 'center', marginBottom: 6,
  },
  quickStatValue: { fontSize: 20, fontWeight: 'bold', color: '#fff' },
  quickStatLabel: { fontSize: 11, color: '#8E8E93', marginTop: 2 },
  quickStatDivider: { width: 1, height: 40, backgroundColor: '#333' },
  scrollView: { flex: 1 },
  scrollContent: { paddingTop: 16 },
  loader: { marginTop: 40 },
  errorContainer: { alignItems: 'center', justifyContent: 'center', padding: 40 },
  errorText: { fontSize: 16, color: '#FF3B30', marginTop: 16, textAlign: 'center' },
  retryButton: {
    marginTop: 16, paddingHorizontal: 24, paddingVertical: 12,
    backgroundColor: '#FF8C00', borderRadius: 10,
  },
  retryText: { color: '#fff', fontWeight: '600' },
  section: { paddingHorizontal: 20, marginBottom: 24 },
  sectionHeader: {
    flexDirection: 'row', justifyContent: 'space-between',
    alignItems: 'center', marginBottom: 14,
  },
  sectionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  sectionDot: { width: 8, height: 8, borderRadius: 4 },
  sectionTitle: { fontSize: 17, fontWeight: '700', color: '#fff' },
  seeAll: { fontSize: 13, color: '#FF8C00', fontWeight: '600' },
  jobCard: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: '#1A1C1E', borderRadius: 14, padding: 14,
    marginBottom: 10, borderWidth: 1, borderColor: '#2A2C2E',
  },
  jobCardLeft: { marginRight: 12 },
  jobIconCircle: {
    width: 44, height: 44, borderRadius: 14,
    justifyContent: 'center', alignItems: 'center',
  },
  jobCardCenter: { flex: 1 },
  jobCardTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 4 },
  jobTitle: { fontSize: 15, fontWeight: '600', color: '#fff', flex: 1 },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  jobInfoRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 2 },
  jobInfoText: { fontSize: 12, color: '#8E8E93', flex: 1 },
  jobCardRight: { alignItems: 'flex-end', marginLeft: 8, gap: 8 },
  jobAmount: { fontSize: 15, fontWeight: 'bold', color: '#34C759' },
  requestCard: {
    backgroundColor: '#1A1C1E', borderRadius: 14, padding: 16,
    marginBottom: 10, borderWidth: 1, borderColor: '#2A2C2E',
  },
  requestCardTop: {
    flexDirection: 'row', justifyContent: 'space-between',
    alignItems: 'center', marginBottom: 8,
  },
  requestTypeBadge: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8,
    backgroundColor: '#222426',
  },
  requestTypeText: { fontSize: 12, fontWeight: '700' },
  requestTime: { fontSize: 12, color: '#8E8E93' },
  requestDescription: { fontSize: 13, color: '#8E8E93', lineHeight: 18, marginBottom: 10 },
  requestInfoRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 4,
  },
  requestInfoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flex: 1,
    minWidth: '45%',
  },
  requestInfoLabel: {
    fontSize: 11,
    color: '#8E8E93',
    flex: 1,
  },
  requestPriceText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#34C759',
  },
  quickActionsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  quickActionCard: {
    width: (width - 50) / 2,
    backgroundColor: '#1A1C1E', borderRadius: 14, padding: 18,
    alignItems: 'center', borderWidth: 1, borderColor: '#2A2C2E',
  },
  quickActionIcon: {
    width: 48, height: 48, borderRadius: 16,
    justifyContent: 'center', alignItems: 'center', marginBottom: 10,
  },
  quickActionLabel: { fontSize: 13, fontWeight: '600', color: '#ccc' },
  emergencyQuickAction: {
    borderColor: '#FF3B3040',
    borderWidth: 2,
    shadowColor: '#FF3B30',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  emptyCard: {
    backgroundColor: '#1A1C1E', borderRadius: 14, padding: 32,
    alignItems: 'center', borderWidth: 1, borderColor: '#2A2C2E',
  },
  emptyTitle: { fontSize: 15, fontWeight: '600', color: '#888', marginTop: 12 },
  emptySubtext: { fontSize: 12, color: '#555', marginTop: 4 },

  // Emergency FAB Styles
  emergencyFAB: {
    position: 'absolute',
    bottom: 30,
    right: 20,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  emergencyPulse: {
    position: 'absolute',
    width: 65,
    height: 65,
    borderRadius: 35,
    backgroundColor: '#FF3B30',
    opacity: 0.3,
  },
  emergencyFABInner: {
    width: 65,
    height: 65,
    borderRadius: 35,
    backgroundColor: '#FF3B30',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 6,
    gap: 1,
    shadowColor: '#FF3B30',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.6,
    shadowRadius: 12,
    elevation: 12,
    borderWidth: 3,
    borderColor: '#fff',
  },
  emergencyFABText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#fff',
    letterSpacing: 1,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },

  // Statistics Dashboard Styles
  statsGrid: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  statCard: {
    flex: 1,
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#2A2C2E',
  },
  statIconContainer: {
    marginBottom: 8,
  },
  statValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: '#8E8E93',
    textAlign: 'center',
  },
  mostUsedCard: {
    flexDirection: 'row',
    backgroundColor: '#1A1C1E',
    borderRadius: 14,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#2A2C2E',
    marginTop: 4,
  },
  mostUsedLeft: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#FFD70020',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  mostUsedRight: {
    flex: 1,
  },
  mostUsedLabel: {
    fontSize: 12,
    color: '#8E8E93',
    marginBottom: 4,
  },
  mostUsedValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
  },
  chartContainer: {
    backgroundColor: '#1A1C1E',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#2A2C2E',
    alignItems: 'center',
  },
  chart: {
    marginVertical: 8,
    borderRadius: 16,
  },
  chartCaption: {
    fontSize: 11,
    color: '#8E8E93',
    textAlign: 'center',
    marginTop: 8,
  },
});
