import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0F1419',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 60,
    paddingBottom: 16,
    backgroundColor: '#17171A',
    borderBottomWidth: 1,
    borderBottomColor: '#2A2A2E',
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 140, 0, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  headerSubtitle: {
    fontSize: 12,
    color: '#8E8E93',
    marginTop: 2,
  },
  refreshBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 140, 0, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollContent: {
    padding: 16,
    paddingTop: 20,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 100,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 14,
    color: '#8E8E93',
  },
  // Balance Card - Horizontal Layout
  balanceCard: {
    backgroundColor: '#17171A',
    borderRadius: 24,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#2A2A2E',
    marginBottom: 24,
    gap: 16,
  },
  balanceIconCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(255, 140, 0, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  balanceContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  balanceLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#8E8E93',
    letterSpacing: 0.3,
  },
  balanceValueContainer: {
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  balanceValue: {
    fontSize: 40,
    fontWeight: '900',
    color: '#FF8C00',
    includeFontPadding: false,
    lineHeight: 48,
    minWidth: 60,
  },
  balanceValueLarge: {
    fontSize: 32,
    fontWeight: '900',
    color: '#FF8C00',
    includeFontPadding: false,
    lineHeight: 40,
    minWidth: 60,
  },
  balanceSub: {
    fontSize: 12,
    fontWeight: '500',
    color: '#6D6D70',
  },
  sharedWalletNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 24,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: 'rgba(255, 140, 0, 0.08)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 140, 0, 0.15)',
  },
  sharedWalletNoteText: {
    fontSize: 11,
    color: '#B0B0B5',
    fontWeight: '500',
    lineHeight: 15,
  },
  cashoutCard: {
    backgroundColor: '#17171A',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#2A2A2E',
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  cashoutInfo: {
    flex: 1,
    paddingRight: 12,
  },
  cashoutTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  cashoutSubtitle: {
    fontSize: 11,
    color: '#8E8E93',
    marginTop: 4,
  },
  cashoutBtn: {
    backgroundColor: '#FF8C00',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
  },
  cashoutBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  // Section
  section: {
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  sectionDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  sectionSubtitle: {
    fontSize: 12,
    color: '#8E8E93',
    marginBottom: 16,
  },
  // Packages Grid
  packagesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  packageCard: {
    width: '30%',
    minWidth: 100,
    flex: 1,
    backgroundColor: '#1C1C1E',
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#2A2A2E',
  },
  packageIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 140, 0, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  packageAmount: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  packageLabel: {
    fontSize: 11,
    color: '#8E8E93',
    marginTop: 2,
  },
  packagePrice: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FF8C00',
    marginTop: 6,
  },
  // Buy Button
  packageBuyBtn: {
    backgroundColor: '#FF8C00',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 24,
    marginTop: 12,
    minWidth: 100,
  },
  packageBuyText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  // Top Up Button
  topUpBtn: {
    backgroundColor: '#FF8C00',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginTop: 10,
    minWidth: 80,
  },
  topUpBtnText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  // Transactions
  txListContainer: {
    maxHeight: 400,
    backgroundColor: '#17171A',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#2A2A2E',
    overflow: 'hidden',
  },
  txList: {
    backgroundColor: '#17171A',
  },
  txRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#2A2A2E',
  },
  txIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#1C1C1E',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  txInfo: {
    flex: 1,
  },
  txType: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  txTime: {
    fontSize: 11,
    color: '#8E8E93',
    marginTop: 2,
  },
  txRight: {
    alignItems: 'flex-end',
  },
  txAmount: {
    fontSize: 15,
    fontWeight: '700',
    color: '#34C759',
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    marginTop: 4,
  },
  statusBadgeText: {
    fontSize: 10,
    fontWeight: '700',
  },
  statusCompleted: {
    backgroundColor: 'rgba(52, 199, 89, 0.15)',
  },
  statusCompletedText: {
    color: '#34C759',
  },
  statusPending: {
    backgroundColor: 'rgba(255, 140, 0, 0.15)',
  },
  statusPendingText: {
    color: '#FF8C00',
  },
  statusFailed: {
    backgroundColor: 'rgba(255, 59, 48, 0.15)',
  },
  statusFailedText: {
    color: '#FF3B30',
  },

  // Payment Modal Styles
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  modalContent: {
    backgroundColor: '#1A1C1E',
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    width: '80%',
    maxWidth: 300,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#fff',
    marginTop: 16,
    marginBottom: 8,
  },
  modalText: {
    fontSize: 14,
    color: '#aaa',
    textAlign: 'center',
    marginBottom: 20,
  },
  cashoutOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  cashoutModal: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#1A1C1E',
    borderRadius: 16,
    padding: 20,
  },
  cashoutModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  cashoutModalSub: {
    fontSize: 12,
    color: '#8E8E93',
    marginTop: 6,
    marginBottom: 16,
  },
  cashoutField: {
    marginBottom: 14,
  },
  cashoutDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  cashoutDetailLabel: {
    fontSize: 12,
    color: '#8E8E93',
  },
  cashoutDetailValue: {
    fontSize: 13,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  cashoutLabel: {
    fontSize: 12,
    color: '#C7C7CC',
    marginBottom: 6,
    fontWeight: '600',
  },
  cashoutChangeBtn: {
    marginTop: 6,
    marginBottom: 12,
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#2A2A2E',
  },
  cashoutChangeText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 12,
  },
  passwordRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  passwordInput: {
    flex: 1,
    paddingRight: 40,
  },
  eyeBtn: {
    position: 'absolute',
    right: 10,
    height: 40,
    width: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cashoutInput: {
    borderWidth: 1,
    borderColor: '#2A2A2E',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#FFFFFF',
    backgroundColor: '#151515',
  },
  cashoutHint: {
    fontSize: 11,
    color: '#8E8E93',
    marginTop: 6,
  },
  cashoutActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 4,
  },
  cashoutActionBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  cashoutCancelBtn: {
    backgroundColor: '#2A2A2E',
  },
  cashoutConfirmBtn: {
    backgroundColor: '#FF8C00',
  },
  cashoutCancelText: {
    color: '#C7C7CC',
    fontWeight: '700',
  },
  cashoutConfirmText: {
    color: '#121212',
    fontWeight: '700',
  },
  modalButton: {
    backgroundColor: '#22c55e',
    paddingHorizontal: 32,
    paddingVertical: 12,
    borderRadius: 8,
    minWidth: 120,
  },
  modalButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },

  // Empty State
  emptyCard: {
    backgroundColor: '#17171A',
    borderRadius: 16,
    padding: 32,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#2A2A2E',
  },
  emptyTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
    marginTop: 12,
  },
  emptySubtext: {
    fontSize: 12,
    color: '#8E8E93',
    marginTop: 4,
  },
});
