import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#111214',
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 40,
  },
  header: {
    alignItems: 'center',
    paddingVertical: 24,
    marginBottom: 12,
  },
  logo: {
    fontSize: 32,
    fontWeight: '700',
    color: '#ECEDEE',
    marginBottom: 4,
    letterSpacing: -0.5,
  },
  tagline: {
    color: '#8E8E93',
    fontSize: 14,
    fontWeight: '400',
  },
  progressContainer: {
    marginVertical: 20,
    marginBottom: 30,
  },
  progressSteps: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    position: 'relative',
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  progressLine: {
    position: 'absolute',
    top: 15,
    left: 35,
    right: 35,
    height: 2,
    backgroundColor: '#2A2C2E',
    zIndex: 1,
  },
  progressBar: {
    position: 'absolute',
    top: 15,
    left: 35,
    height: 2,
    backgroundColor: '#FF8C00',
    zIndex: 2,
  },
  stepContainer: {
    alignItems: 'center',
    zIndex: 3,
    flex: 1,
  },
  step: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#1A1C1E',
    borderWidth: 2,
    borderColor: '#2A2C2E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepActive: {
    borderColor: '#FF8C00',
    backgroundColor: '#FF8C00',
  },
  stepCompleted: {
    borderColor: '#34C759',
    backgroundColor: '#34C759',
  },
  stepNumber: {
    fontSize: 14,
    fontWeight: '600',
    color: '#8E8E93',
  },
  stepNumberActive: {
    color: '#111214',
  },
  stepLabel: {
    fontSize: 11,
    lineHeight: 14,
    color: '#8E8E93',
    marginTop: 8,
    textAlign: 'center',
    minHeight: 16,
  },
  stepLabelActive: {
    color: '#FF8C00',
    fontWeight: '600',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#ECEDEE',
    marginBottom: 20,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#2A2C2E',
  },
  formContainer: {
    width: '100%',
    backgroundColor: '#1A1C1E',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: '#2A2C2E',
  },
  inputContainer: {
    marginBottom: 16,
  },
  label: {
    fontSize: 14,
    fontWeight: '500',
    color: '#ECEDEE',
    marginBottom: 6,
  },
  required: {
    color: '#FF8C00',
    marginLeft: 2,
  },
  optional: {
    fontStyle: 'italic',
    color: '#8E8E93',
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#2A2C2E',
    borderRadius: 10,
    backgroundColor: '#151718',
    paddingHorizontal: 10,
  },
  inputWrapperFocused: {
    borderColor: '#FF8C00',
  },
  input: {
    flex: 1,
    paddingVertical: 10,
    fontSize: 15,
    color: '#ECEDEE',
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: '#2A2C2E',
    borderRadius: 10,
    backgroundColor: '#151718',
    overflow: 'hidden',
  },
  picker: {
    height: 50,
    color: '#ECEDEE',
  },
  pickerLoadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
    paddingLeft: 4,
  },
  pickerLoadingText: {
    fontSize: 12,
    color: '#FF8C00',
    marginLeft: 6,
    fontStyle: 'italic',
  },
  dateButton: {
    borderWidth: 1,
    borderColor: '#2A2C2E',
    borderRadius: 10,
    padding: 10,
    backgroundColor: '#151718',
  },
  selectButton: {
    minHeight: 44,
    borderWidth: 1,
    borderColor: '#2A2C2E',
    borderRadius: 10,
    backgroundColor: '#151718',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectButtonDisabled: {
    opacity: 0.6,
  },
  selectButtonText: {
    color: '#ECEDEE',
    fontSize: 15,
    flex: 1,
    paddingRight: 8,
  },
  selectButtonPlaceholder: {
    color: '#999',
    fontSize: 15,
    flex: 1,
    paddingRight: 8,
  },
  dateText: {
    fontSize: 15,
    color: '#ECEDEE',
  },
  placeholderText: {
    fontSize: 15,
    color: '#999',
  },
  eyeButton: {
    padding: 4,
    marginLeft: 8,
  },
  buttonContainer: {
    flexDirection: 'column',
    gap: 12,
    marginTop: 30,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#2A2C2E',
  },
  button: {
    width: '100%',
    backgroundColor: '#FF8C00',
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
  },
  buttonSecondary: {
    backgroundColor: '#151718',
    borderWidth: 1,
    borderColor: '#2A2C2E',
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  buttonTextSecondary: {
    color: '#ECEDEE',
  },
  buttonSubmit: {
    backgroundColor: '#34C759',
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#2A2C2E',
  },
  footerText: {
    color: '#A7ADB3',
    fontSize: 15,
  },
  linkText: {
    color: '#FF8C00',
    fontSize: 15,
    fontWeight: '600',
    marginLeft: 4,
  },
  copyright: {
    marginTop: 'auto',
    paddingTop: 20,
    alignItems: 'center',
  },
  copyrightText: {
    color: '#6E7378',
    fontSize: 13,
  },
});