# Generated by Django 6.0.1 on 2026-04-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_token_price', models.DecimalField(decimal_places=2, default=1.0, help_text='Price per token in PHP', max_digits=10)),
                ('min_token_purchase', models.IntegerField(default=1, help_text='Minimum tokens per purchase')),
                ('max_token_purchase', models.IntegerField(default=1000, help_text='Maximum tokens per purchase')),
                ('base_distance_fee', models.DecimalField(decimal_places=2, default=50.0, help_text='Base fee in PHP', max_digits=10)),
                ('price_per_km', models.DecimalField(decimal_places=2, default=15.0, help_text='Price per km in PHP', max_digits=10)),
                ('free_distance_km', models.DecimalField(decimal_places=2, default=2.0, help_text='Free distance in km before charging', max_digits=5)),
                ('traffic_low_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier for low traffic', max_digits=5)),
                ('traffic_medium_multiplier', models.DecimalField(decimal_places=2, default=1.25, help_text='Multiplier for medium traffic', max_digits=5)),
                ('traffic_high_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='Multiplier for high traffic', max_digits=5)),
                ('convenience_fee_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Convenience fee percentage', max_digits=5)),
                ('convenience_fee_fixed', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed convenience fee in PHP', max_digits=10)),
                ('min_job_price', models.DecimalField(decimal_places=2, default=100.0, help_text='Minimum job price in PHP', max_digits=10)),
                ('platform_commission_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Platform commission percentage', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
            },
        ),
    ]
