# Generated by Django 6.0.1 on 2026-04-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_pricingconfiguration_token_deduction_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingconfiguration',
            name='disbursement_fee',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='PayMongo InstaPay fee per disbursement', max_digits=6),
        ),
    ]
