# Generated by Django 6.0.1 on 2026-01-28 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('shops', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopservice',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
        migrations.AddField(
            model_name='shopservicemechanic',
            name='mechanic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mechanic'),
        ),
        migrations.AddField(
            model_name='shopservicemechanic',
            name='shop_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.shopservice'),
        ),
        migrations.AddField(
            model_name='shopspecialty',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
        migrations.AddField(
            model_name='shopspecialty',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.specialty'),
        ),
        migrations.AddField(
            model_name='mechanicspecialty',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.specialty'),
        ),
        migrations.AddField(
            model_name='servicetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.tag'),
        ),
    ]
