# Generated by Django 6.0.1 on 2026-02-09 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_refactor_pricing_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mechanicservice',
            new_name='services_me_mechani_d6a199_idx',
            old_name='services_me_mechani_idx',
        ),
        migrations.RenameIndex(
            model_name='mechanicservice',
            new_name='services_me_service_124121_idx',
            old_name='services_me_service_idx',
        ),
        migrations.RemoveField(
            model_name='service',
            name='min_price',
        ),
        migrations.AddField(
            model_name='service',
            name='minimum_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Informational minimum price set by admin. Mechanics can set their own prices freely.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='mechanicservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mechanicservice',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text="Mechanic's price for this service. Set freely by the mechanic.", max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='mechanicservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
