# Generated by Django 4.2.11 on 2026-03-08 04:28

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('services', '0004_rename_services_me_mechani_idx_services_me_mechani_d6a199_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Shop's price for this service.", max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='shopservice',
            unique_together={('shop', 'service')},
        ),
    ]
