# Generated by Django 6.0.1 on 2026-03-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_shopservice_created_at_shopservice_price_and_more'),
        ('shops', '0001_initial'),
        ('users', '0008_tokentransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechanicspecialty',
            old_name='created_at',
            new_name='requested_at',
        ),
        migrations.RenameField(
            model_name='shopspecialty',
            old_name='created_at',
            new_name='requested_at',
        ),
        migrations.AddField(
            model_name='mechanicspecialty',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mechanicspecialty',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mechanicspecialty',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='shopspecialty',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopspecialty',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopspecialty',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='mechanicspecialty',
            unique_together={('mechanic', 'specialty')},
        ),
        migrations.AlterUniqueTogether(
            name='shopspecialty',
            unique_together={('shop', 'specialty')},
        ),
    ]
