# Generated by Django 6.0.1 on 2026-03-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_rename_created_at_mechanicspecialty_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicspecialty',
            name='proof_document',
            field=models.FileField(blank=True, help_text='Upload certificate, license, or supporting document.', null=True, upload_to='mechanics/specialty_docs/'),
        ),
        migrations.AddField(
            model_name='mechanicspecialty',
            name='source_description',
            field=models.TextField(blank=True, help_text="Explanation of the mechanic's experience or training.", null=True),
        ),
        migrations.AddField(
            model_name='mechanicspecialty',
            name='source_type',
            field=models.CharField(choices=[('certification', 'Certification'), ('license', 'License'), ('training', 'Training'), ('experience', 'Work Experience'), ('other', 'Other')], default='other', help_text="Type of proof showing the mechanic's expertise.", max_length=50),
        ),
        migrations.AddField(
            model_name='shopspecialty',
            name='proof_document',
            field=models.FileField(blank=True, null=True, upload_to='shops/specialty_docs/'),
        ),
        migrations.AddField(
            model_name='shopspecialty',
            name='source_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopspecialty',
            name='source_type',
            field=models.CharField(choices=[('certification', 'Certification'), ('license', 'License'), ('training', 'Training'), ('experience', 'Work Experience'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
