# Generated by Django 6.0.1 on 2026-04-20 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_serviceaddon_shop'),
        ('users', '0013_mechanic_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaddon',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_add_ons', to='users.mechanic'),
        ),
    ]
