# Re-export admin views for backward compatibility
from .views.admin import (
    admin_list_vehicle_types,
    admin_get_vehicle_type,
    admin_create_vehicle_type,
    admin_update_vehicle_type,
    admin_delete_vehicle_type,
    admin_list_vehicle_brands,
    admin_get_vehicle_brand,
    admin_create_vehicle_brand,
    admin_update_vehicle_brand,
    admin_delete_vehicle_brand,
    admin_list_vehicle_models,
    admin_get_vehicle_model,
    admin_create_vehicle_model,
    admin_update_vehicle_model,
    admin_delete_vehicle_model,
)

__all__ = [
    'admin_list_vehicle_types',
    'admin_get_vehicle_type',
    'admin_create_vehicle_type',
    'admin_update_vehicle_type',
    'admin_delete_vehicle_type',
    'admin_list_vehicle_brands',
    'admin_get_vehicle_brand',
    'admin_create_vehicle_brand',
    'admin_update_vehicle_brand',
    'admin_delete_vehicle_brand',
    'admin_list_vehicle_models',
    'admin_get_vehicle_model',
    'admin_create_vehicle_model',
    'admin_update_vehicle_model',
    'admin_delete_vehicle_model',
]
