# Generated by Django 6.0.1 on 2026-02-01 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('license', 'License'), ('certification', 'Certification'), ('id', 'Id'), ('others', 'Others')], max_length=50)),
                ('document_file', models.FileField(upload_to='mechanics/docs/')),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('date_expiry', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mechanic')),
            ],
        ),
    ]
