# Generated by Django 6.0.1 on 2026-02-04 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('users', '0002_mechanicdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mechanics', to='shops.shop'),
        ),
    ]
