# Generated by Django 6.0.1 on 2026-02-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_mechanic_bio_mechanicreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_active_role',
            field=models.CharField(blank=True, help_text='Last role the user was using before logout', max_length=20, null=True),
        ),
    ]
