# Generated by Django 4.2.11 on 2026-03-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='tokens_balance',
            field=models.IntegerField(default=0),
        ),
    ]
