# Generated by Django 6.0.1 on 2026-03-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_tokentransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='rejection_note',
            field=models.TextField(blank=True, help_text='Reason provided by admin if the mechanic request is rejected.', null=True),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Admin approval status of the mechanic account.', max_length=20),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='rejection_note',
            field=models.TextField(blank=True, help_text='Admin explanation when the shop owner application is rejected.', null=True),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Admin approval status of the shop owner.', max_length=20),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
