# Generated by Django 6.0.1 on 2026-04-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_mechanic_rejection_note_mechanic_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('gcash', 'GCash'), ('maya', 'Maya')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='payout_number',
            field=models.CharField(blank=True, help_text='GCash or Maya number for receiving payouts', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('gcash', 'GCash'), ('maya', 'Maya')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='payout_number',
            field=models.CharField(blank=True, help_text='GCash or Maya number for receiving payouts', max_length=11, null=True),
        ),
    ]
