# Generated by Django 6.0.1 on 2026-04-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_mechanic_payout_method_mechanic_payout_number_and_more'),
        ('users', '0011_remove_passwordchangeverification'),
    ]

    operations = [
    ]
