# Generated by Django 6.0.1 on 2026-04-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20260418_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='When true, mechanic is blocked from accepting new jobs'),
        ),
    ]
