# Generated by Django 6.0.1 on 2026-04-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_mechanic_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, help_text='Mechanic cannot accept jobs until this timestamp', null=True),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='no_show_count',
            field=models.PositiveIntegerField(default=0, help_text='Total no-show violations recorded for anti-abuse penalties'),
        ),
    ]
