# Generated by Django 6.0.1 on 2026-04-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_mechanic_no_show_fields'),
    ]

    operations = [
        # Column may already exist on some DBs (manual / partial apply). Keep Django state in sync
        # without failing on duplicate column.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='shopowner',
                    name='tokens_balance',
                    field=models.IntegerField(default=0),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE users_shopowner "
                        "ADD COLUMN IF NOT EXISTS tokens_balance integer NOT NULL DEFAULT 0;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE users_shopowner DROP COLUMN IF EXISTS tokens_balance;"
                    ),
                ),
            ],
        ),
    ]
