# Generated by Django 6.0.1 on 2026-04-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_shopowner_tokens_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_superadmin',
            field=models.BooleanField(default=False, help_text='If true, admin has access to Trust and Safety and Wallet & Token Ledger'),
        ),
    ]
