# Generated by Django 6.0.1 on 2026-04-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_admin_is_superadmin'),
        ('users', '0017_account_deactivated_at'),
    ]

    operations = [
    ]
