# Generated by Django 6.0.1 on 2026-04-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_merge_20260423_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenpurchase',
            name='ewallet_source_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tokenpurchase',
            name='external_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
