# Generated by Django 6.0.1 on 2026-04-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_tokenpurchase_ewallet_source_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountaddress',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountaddress',
            name='is_main',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountaddress',
            name='label',
            field=models.CharField(default='Main Branch', max_length=50),
        ),
        migrations.AddField(
            model_name='accountaddress',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountaddress',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AccountBranchLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('formatted_address', models.CharField(blank=True, max_length=255, null=True)),
                ('barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(max_length=50)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_locations', to='users.account')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='accountbranchlocation',
            constraint=models.UniqueConstraint(fields=('account', 'label'), name='unique_branch_label_per_account'),
        ),
        migrations.AddConstraint(
            model_name='accountbranchlocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('account',), name='unique_main_branch_location_per_account'),
        ),
    ]
