# Generated by Django 6.0.1 on 2026-04-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_account_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSOTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(db_index=True, max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contact_number', 'is_verified', 'expires_at'], name='users_smsot_contact_8add25_idx'), models.Index(fields=['created_at'], name='users_smsot_created_96fcab_idx')],
            },
        ),
    ]
