# Generated by Django 6.0.1 on 2026-04-25 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_smsotpverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='tokens_balance',
        ),
        migrations.RemoveField(
            model_name='shopowner',
            name='tokens_balance',
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='users.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
