# Generated by Django 6.0.1 on 2026-04-25 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shopmechanic_is_active'),
        ('users', '0025_remove_mechanic_tokens_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='employees/profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
                ('shop', models.ForeignKey(help_text='The shop this employee works for', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='shops.shop')),
            ],
        ),
    ]
