# Generated by Django 6.0.1 on 2026-04-26 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_shopemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsotpverification',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to='users.account'),
        ),
    ]
