# Generated by Django 6.0.1 on 2026-04-30 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_smsotpverification_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('gcash', 'GCash'), ('maya', 'Maya')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='payout_number',
            field=models.CharField(blank=True, help_text='GCash or Maya number for receiving payouts (stored at account level)', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CashOutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
                ('tokens', models.IntegerField()),
                ('amount_php', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_method', models.CharField(max_length=10)),
                ('payout_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
            ],
        ),
    ]
