"""
Django settings for MainBackend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

load_dotenv(os.path.join(BASE_DIR, '.env'), override=True)
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "dev-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'corsheaders',
    'users',
    'shops',
    'services',
    'bookings',
    'notification',
    'chat',
    'storages',
    'mechconnect_ai',
    'pricing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = 'MainBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'MainBackend.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

USE_SUPABASE = os.getenv('USE_SUPABASE', 'False') == 'True'

if USE_SUPABASE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('SUPABASE_NAME'),
            'USER': os.getenv('SUPABASE_USER'),
            'PASSWORD': os.getenv('SUPABASE_PASSWORD'),
            'HOST': os.getenv('SUPABASE_HOST'),
            'PORT': os.getenv('SUPABASE_PORT'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('LOCAL_NAME'),
            'USER': os.getenv('LOCAL_USER'),
            'PASSWORD': os.getenv('LOCAL_PASSWORD'),
            'HOST': os.getenv('LOCAL_HOST'),
            'PORT': os.getenv('LOCAL_PORT'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"


# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.authentication.JWTAuthentication',
        'users.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8081",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8081",
    "https://mechconnectse2-production.up.railway.app"
]

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Brevo Gmail API config
BREVO_API_KEY = os.getenv('BREVO_API_KEY', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', '')
EMAIL_TIMEOUT = 10

# External routing/traffic API keys
ORS_API_KEY = os.getenv('ORS_API_KEY', os.getenv('EXPO_PUBLIC_ORS_API_KEY', ''))
TOMTOM_API_KEY = os.getenv('TOMTOM_API_KEY', os.getenv('EXPO_PUBLIC_TOMTOM_API_KEY', ''))

# Supabase Storage Configuration
USE_S3 = os.environ.get("USE_S3", "False") == "True"
if USE_S3:
    print("=" * 50)
    print("USE_S3:", USE_S3)
    print("AWS_ACCESS_KEY_ID:", os.environ.get("SUPABASE_ACCESS_KEY", "NOT SET")[:10] + "...")
    print("AWS_SECRET_ACCESS_KEY:", os.environ.get("SUPABASE_SECRET_KEY", "NOT SET")[:10] + "...")
    print("AWS_STORAGE_BUCKET_NAME:", os.environ.get("SUPABASE_STORAGE_BUCKET"))
    print("AWS_S3_ENDPOINT_URL:", os.environ.get("SUPABASE_S3_ENDPOINT"))
    print("AWS_S3_REGION_NAME:", os.environ.get("SUPABASE_S3_REGION"))
    print("=" * 50)
    
    AWS_ACCESS_KEY_ID = os.environ.get("SUPABASE_ACCESS_KEY")
    AWS_SECRET_ACCESS_KEY = os.environ.get("SUPABASE_SECRET_KEY")
    AWS_STORAGE_BUCKET_NAME = os.environ.get("SUPABASE_STORAGE_BUCKET")
    AWS_S3_ENDPOINT_URL = os.environ.get("SUPABASE_S3_ENDPOINT")
    AWS_S3_REGION_NAME = os.environ.get("SUPABASE_S3_REGION")
    
    # Supabase-specific settings
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False 
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_ADDRESSING_STYLE = 'path'  
    AWS_S3_USE_SSL = True
    AWS_S3_VERIFY = True
    
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    STORAGES = {
        "default": {
            "BACKEND": "MainBackend.supabase_storage.SupabaseStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = f"https://tsokmagrbtfuuzlemufw.supabase.co/storage/v1/object/public/{AWS_STORAGE_BUCKET_NAME}/"
    MEDIA_ROOT = ''
else:
    # Media files configuration (used for local storage and as fallback)
    print("USE_S3:", USE_S3)
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'bookings': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'MainBackend.supabase_storage': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'boto3': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'botocore': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        's3transfer': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}